// For specification see 
// https://protobuf.dev/programming-guides/proto3/
// https://protobuf.dev/reference/go/go-generated/
// https://protobuf.dev/reference/python/python-generated/
syntax = "proto3";
package api_service.v1;

option go_package = "github.com/gobitfly/beaconchain-backend/model";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "External Service API"
    version: "1.0"
  }
  security_definitions: {
    security: {
      key: "ApiKeyAuth"
      value: {
        type: TYPE_API_KEY
        name: "authorization"
        in: IN_HEADER
        description: "Authorization header with value: Bearer <token>"
      }
    }
  }
  security: {
    security_requirement: {
      key: "ApiKeyAuth"
      value: {}  // apply to all endpoints
    }
  }
};


import "google/api/annotations.proto";
import "google/protobuf/descriptor.proto";
import "protoc-gen-openapiv2/options/annotations.proto";


//////////////////////////////////////////////////
/////////////// Service Definition ///////////////
//////////////////////////////////////////////////


message RateLimitSettings {
  float steady_rate = 1;
  int32 bucket_capacity = 2;
}

message RateLimitsPerTier {
  optional RateLimitSettings free = 1;
  optional RateLimitSettings hobbyist = 2;
  optional RateLimitSettings business = 3;
  optional RateLimitSettings scale = 4;
}

extend google.protobuf.MethodOptions {
  RateLimitsPerTier rate_limits_per_tier = 50001;
}




service ExternalService {

  // Get execution blocks by execution block number
  rpc ExecutionBlock (ExecutionBlockRequest) returns (ExecutionBlockResponse) {
    option (rate_limits_per_tier) = {
      free: { steady_rate: 1.0, bucket_capacity: 1 }
      hobbyist: { steady_rate: 2.0, bucket_capacity: 2 }
      business: { steady_rate: 5.0, bucket_capacity: 5 }
      scale: { steady_rate: 10.0, bucket_capacity: 10 }
    };
    option (google.api.http) = {
      get: "/api/v1/execution/block/{block_number}"
    };
  }
}

/////////////////////////////////////////////////
/////////// Request/Response Definition ////////////
/////////////////////////////////////////////////

/* ExecutionBlock */
// A request to get a summary of a particular execution block
message ExecutionBlockRequest {
  // Provide one or more execution block numbers. Comma separated up to max 100.
  string block_number = 1;
}

// A Response containing a summary of the execution block
message ExecutionBlockResponse {
  string status = 1;
  BlockSummary data = 2;
}


//////////////////////////////////////////////////
/////////////// Message Definition ///////////////
//////////////////////////////////////////////////

message BlockSummary {
  string block_hash = 1;
  string block_number = 2;
}



