// For specification see 
// https://protobuf.dev/programming-guides/proto3/
// https://protobuf.dev/reference/go/go-generated/
// https://protobuf.dev/reference/python/python-generated/
syntax = "proto3";
package api_service.v1;

option go_package = "github.com/gobitfly/beaconchain-backend/model";

import "google/api/annotations.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/descriptor.proto";


//////////////////////////////////////////////////
/////////////// Service Definition ///////////////
//////////////////////////////////////////////////

extend google.protobuf.MethodOptions {
  bool require_authentication = 50002;
}

service InternalService {
  rpc CreateAPIKey (CreateAPIKeyRequest) returns (CreateAPIKeyResponse) {
    option (google.api.http) = {
      post: "/api-keys"
    };
    option (require_authentication) = true;
  }
  rpc DeleteAPIKey (DeleteAPIKeyRequest) returns (DeleteAPIKeyResponse) {
    option (google.api.http) = {
      delete: "/api-keys/{name}"
    };
    option (require_authentication) = true;
  }
  rpc DisableAPIKey (DisableAPIKeyRequest) returns (DisableAPIKeyResponse) {
    option (google.api.http) = {
      post: "/api-keys/{name}/disable"
    };
    option (require_authentication) = true;
  }
  rpc EnableAPIKey (EnableAPIKeyRequest) returns (EnableAPIKeyResponse) {
    option (google.api.http) = {
      post: "/api-keys/{name}/enable"
    };
    option (require_authentication) = true;
  }
  rpc GetAPIKeys (GetAPIKeysRequest) returns (GetAPIKeysResponse) {
    option (google.api.http) = {
      get: "/api-keys"
    };
    option (require_authentication) = true;
  }
  rpc GetAPIKey (GetAPIKeyRequest) returns (GetAPIKeyResponse) {
    option (google.api.http) = {
      get: "/api-keys/{name}"
    };
    option (require_authentication) = true;
  }

}

/////////////////////////////////////////////////
/////////// Request/Response Definition ////////////
/////////////////////////////////////////////////


// == API Key Management ==

// API Key names must follow specific rules to ensure consistency and security.
// The 'name' field must be a string matching the pattern: ^[A-Za-z0-9_.-]{3,35}$
// This regex enforces that the name is 3 to 35 characters long and contains only
// uppercase and lowercase letters, digits, underscores (_), periods (.), or hyphens (-).

message CreateAPIKeyRequest {
  string name = 1 [
    (buf.validate.field).string = {
      pattern: "^[A-Za-z0-9_.-]{3,35}$",
    }
  ];
}


message CreateAPIKeyResponse {
  string raw_api_key = 1; 
  APIKey api_key = 2;
}

message DeleteAPIKeyRequest {
  string name = 1 [
    (buf.validate.field).string = {
      pattern: "^[A-Za-z0-9_.-]{3,35}$",
    }
  ];
}

message DeleteAPIKeyResponse {
  // nil; no response
}

message DisableAPIKeyRequest {
  string name = 1 [
    (buf.validate.field).string = {
      pattern: "^[A-Za-z0-9_.-]{3,35}$",
    }
  ];
}

message DisableAPIKeyResponse {
  APIKey api_key = 1;
}

message EnableAPIKeyRequest {
  string name = 1 [
    (buf.validate.field).string = {
      pattern: "^[A-Za-z0-9_.-]{3,35}$",
    }
  ];
}

message EnableAPIKeyResponse {
  APIKey api_key = 1;
}

message GetAPIKeysRequest {
}

message GetAPIKeysResponse {
  repeated APIKey api_keys = 1;
}

message GetAPIKeyRequest {
  string name = 1 [
    (buf.validate.field).string = {
      pattern: "^[A-Za-z0-9_.-]{3,35}$",
    }
  ];
}

message GetAPIKeyResponse {
  APIKey api_key = 1;
}


//////////////////////////////////////////////////
/////////////// Message Definition ///////////////
//////////////////////////////////////////////////


message APIKey {
  string name = 1;
  string short_key = 2;
  google.protobuf.Timestamp created_at = 3;
  optional google.protobuf.Timestamp last_used_at = 4;
  optional google.protobuf.Timestamp disabled_at = 5;
}

