// For specification see 
// https://protobuf.dev/programming-guides/proto3/
// https://protobuf.dev/reference/go/go-generated/
// https://protobuf.dev/reference/python/python-generated/
syntax = "proto3";
package api_service.v1;

option go_package = "github.com/gobitfly/beaconchain-api/model";

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

//////////////////////////////////////////////////
/////////////// Service Definition ///////////////
//////////////////////////////////////////////////

service InternalService {
  
  // Creates a new Validator Dashboard
  rpc CreateValidatorDashboard (CreateValidatorDashboardRequest) returns (CreateValidatorDashboardResponse) {
    option (google.api.http) = {
      post: "/api/i/validatorDashboard"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      extensions: {
        key: "x-google-backend"
        value: {
          struct_value: {
            fields: {
              key: "address"
              // will be set by terraform templatefile()
              value: { string_value: "${CLOUD_RUN_URL}" }
            }
            fields: {
              key: "path_translation"
              value: { string_value: "APPEND_PATH_TO_ADDRESS" }
            }
          }
        }
      }
    };
  }

  // Retrieves a Validator Dashboard by its Id
  rpc GetValidatorDashboard (GetValidatorDashboardRequest) returns (GetValidatorDashboardResponse) {
    option (google.api.http) = {
      get: "/api/i/validatorDashboard/{dashboard_id}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      extensions: {
        key: "x-google-backend"
        value: {
          struct_value: {
            fields: {
              key: "address"
              // will be set by terraform templatefile()
              value: { string_value: "${CLOUD_RUN_URL}" }
            }
            fields: {
              key: "path_translation"
              value: { string_value: "APPEND_PATH_TO_ADDRESS" }
            }
          }
        }
      }
    };
  }

  // Retrieves multiple Validator Dashboards by ID or for the entire account
  rpc ListValidatorDashboards (ListValidatorDashboardsRequest) returns (ListValidatorDashboardsResponse) {
    option (google.api.http) = {
      get: "/api/i/validatorDashboard"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      extensions: {
        key: "x-google-backend"
        value: {
          struct_value: {
            fields: {
              key: "address"
              // will be set by terraform templatefile()
              value: { string_value: "${CLOUD_RUN_URL}" }
            }
            fields: {
              key: "path_translation"
              value: { string_value: "APPEND_PATH_TO_ADDRESS" }
            }
          }
        }
      }
    };
  }

  // Deletes a Validator Dashboard by its Id
  rpc DeleteValidatorDashboard (DeleteValidatorDashboardRequest) returns (DeleteValidatorDashboardResponse) {
    option (google.api.http) = {
      delete: "/api/i/validatorDashboard/{dashboard_id}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      extensions: {
        key: "x-google-backend"
        value: {
          struct_value: {
            fields: {
              key: "address"
              // will be set by terraform templatefile()
              value: { string_value: "${CLOUD_RUN_URL}" }
            }
            fields: {
              key: "path_translation"
              value: { string_value: "APPEND_PATH_TO_ADDRESS" }
            }
          }
        }
      }
    };
  }

}

/////////////////////////////////////////////////
/////////// Request/Response Definition ////////////
/////////////////////////////////////////////////

// Create
message CreateValidatorDashboardRequest {
  // nil
}

message CreateValidatorDashboardResponse {
  ValidatorDashboard dashboard = 1;
}

// Get
message GetValidatorDashboardRequest {
  string dashboard_id = 1;

}

message GetValidatorDashboardResponse {
  ValidatorDashboard dashboard = 1;

}

// List
message ListValidatorDashboardsRequest {
  repeated string dashboard_id = 1;
}

message ListValidatorDashboardsResponse {
  repeated ValidatorDashboard dashboards = 1;
}

// Modify
message ModifyValidatorDashboardsRequest {
  string dashboard_id = 1;
  // Whether the Dashboard is publicly visible
  optional bool is_public = 2;
}

message ModifyValidatorDashboardsResponse {
  ValidatorDashboard dashboard = 1;
}

// Delete
message DeleteValidatorDashboardRequest {
  string dashboard_id = 1;
}

message DeleteValidatorDashboardResponse {
  // nil; no response
}



//////////////////////////////////////////////////
/////////////// Message Definition ///////////////
//////////////////////////////////////////////////

message ValidatorDashboard {
  string dashboard_id = 1;
  bool is_public = 2;
}



