// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: archiver.go

export interface ArchiverDashboard {
  DashboardId: number /* uint64 */;
  IsArchived: boolean;
  GroupCount: number /* uint64 */;
  ValidatorCount: number /* uint64 */;
}
export interface ArchiverDashboardArchiveReason {
  DashboardId: number /* uint64 */;
  ArchivedReason: any /* enums.VDBArchivedReason */;
}
