// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */

//////////
// source: error_codes.go

export type ErrorCode = string;
export const ErrorEffectiveBalanceTooHigh: ErrorCode = "MAX_EB_EXCEEDED";
export const ErrorBadRequest: ErrorCode = "BAD_REQUEST";
export const ErrorInternalServerError: ErrorCode = "INTERNAL_SERVER_ERROR";
export const ErrorNotFound: ErrorCode = "NOT_FOUND";
export const ErrorUnauthorized: ErrorCode = "UNAUTHORIZED";
export const ErrorForbidden: ErrorCode = "FORBIDDEN";
export const ErrorConflict: ErrorCode = "CONFLICT";
export const ErrorTooManyRequests: ErrorCode = "TOO_MANY_REQUESTS";
export const ErrorGone: ErrorCode = "GONE";
export const ErrorServiceUnavailable: ErrorCode = "SERVICE_UNAVAILABLE";
