// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
import type { ApiDataResponse } from './common'

//////////
// source: machine_metrics.go

export interface MachineMetricsData {
  system_metrics: (any /* types.MachineMetricSystem */ | undefined)[];
  validator_metrics: (any /* types.MachineMetricValidator */ | undefined)[];
  node_metrics: (any /* types.MachineMetricNode */ | undefined)[];
}
export type GetUserMachineMetricsRespone = ApiDataResponse<MachineMetricsData>;
