// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
import type { Address, Hash } from './common'

//////////
// source: search.go

export interface PostSearchRequest {
  input: string;
  networks?: (number | string)[];
  types?: string[];
}
export interface SearchValidator {
  index: number /* uint64 */;
  public_key: string;
}
export interface SearchValidatorList {
  validators: number /* uint64 */[];
}
export interface SearchValidatorsByDepositAddress {
  ens_name?: string;
  deposit_address: string;
  count: number /* uint64 */;
}
export interface SearchValidatorsByWithdrawalCredential {
  ens_name?: string;
  withdrawal_credential: string;
  count: number /* uint64 */;
}
export interface SearchValidatorsByGraffiti {
  graffiti: string;
  hex: string;
  count: number /* uint64 */;
}
export interface SearchAddress {
  address: Address;
}
export interface SearchEnsName {
  ens_name: string;
}
export interface SearchTransaction {
  transaction_hash: Hash;
}
export interface SearchBlock {
  block_number: number /* uint64 */;
}
export interface SearchSlot {
  slot: number /* uint64 */;
}
export interface SearchEpoch {
  epoch: number /* uint64 */;
}
export interface SearchToken {
  address: Address;
  token: 'ERC20' | 'ERC721' | 'ERC1155'; // currently only erc20 tokens can be found
}
export interface SearchResult {
  type: string;
  chain_id: number /* uint64 */;
  value: any;
}
export interface InternalPostSearchResponse {
  data: ({ type: 'validator'; chain_id: number; value: SearchValidator } | { type: 'validator_list'; chain_id: number; value: SearchValidatorList } | { type: 'validators_by_deposit_address'; chain_id: number; value: SearchValidatorsByDepositAddress } | { type: 'validators_by_withdrawal_credential'; chain_id: number; value: SearchValidatorsByWithdrawalCredential } | { type: 'validators_by_graffiti'; chain_id: number; value: SearchValidatorsByGraffiti } | { type: 'address'; chain_id: number; value: SearchAddress } | { type: 'transaction'; chain_id: number; value: SearchTransaction } | { type: 'block'; chain_id: number; value: SearchBlock } | { type: 'epoch'; chain_id: number; value: SearchEpoch } | { type: 'token'; chain_id: number; value: SearchToken } | { type: 'slot'; chain_id: number; value: SearchSlot } | { type: 'ens_name'; chain_id: number; value: SearchEnsName })[];
}
