// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	consapitypes "github.com/gobitfly/beaconchain/pkg/consapi/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/gobitfly/beaconchain/pkg/commons/types"
)

// SlotExporterClient is an autogenerated mock type for the SlotExporterClient type
type SlotExporterClient struct {
	mock.Mock
}

// GetBalancesForEpoch provides a mock function with given fields: epoch
func (_m *SlotExporterClient) GetBalancesForEpoch(epoch int64) (map[uint64]uint64, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetBalancesForEpoch")
	}

	var r0 map[uint64]uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (map[uint64]uint64, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(int64) map[uint64]uint64); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockBySlot provides a mock function with given fields: slot
func (_m *SlotExporterClient) GetBlockBySlot(slot uint64) (*types.Block, error) {
	ret := _m.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockBySlot")
	}

	var r0 *types.Block
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.Block, error)); ok {
		return rf(slot)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.Block); ok {
		r0 = rf(slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(slot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockHeader provides a mock function with given fields: slot
func (_m *SlotExporterClient) GetBlockHeader(slot uint64) (*consapitypes.StandardBeaconHeaderResponse, error) {
	ret := _m.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeader")
	}

	var r0 *consapitypes.StandardBeaconHeaderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*consapitypes.StandardBeaconHeaderResponse, error)); ok {
		return rf(slot)
	}
	if rf, ok := ret.Get(0).(func(uint64) *consapitypes.StandardBeaconHeaderResponse); ok {
		r0 = rf(slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consapitypes.StandardBeaconHeaderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(slot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetChainHead provides a mock function with no fields
func (_m *SlotExporterClient) GetChainHead() (*types.ChainHead, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainHead")
	}

	var r0 *types.ChainHead
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ChainHead, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ChainHead); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ChainHead)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochAssignments provides a mock function with given fields: epoch
func (_m *SlotExporterClient) GetEpochAssignments(epoch uint64) (*types.EpochAssignments, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetEpochAssignments")
	}

	var r0 *types.EpochAssignments
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.EpochAssignments, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.EpochAssignments); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.EpochAssignments)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorParticipation provides a mock function with given fields: epoch
func (_m *SlotExporterClient) GetValidatorParticipation(epoch uint64) (*types.ValidatorParticipation, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorParticipation")
	}

	var r0 *types.ValidatorParticipation
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.ValidatorParticipation, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.ValidatorParticipation); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ValidatorParticipation)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorQueue provides a mock function with no fields
func (_m *SlotExporterClient) GetValidatorQueue() (*types.ValidatorQueue, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorQueue")
	}

	var r0 *types.ValidatorQueue
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ValidatorQueue, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ValidatorQueue); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ValidatorQueue)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSlotExporterClient creates a new instance of SlotExporterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotExporterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotExporterClient {
	mock := &SlotExporterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
