// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/gobitfly/beaconchain/pkg/consapi/types"
)

// ValidatorClient is an autogenerated mock type for the ValidatorClient type
type ValidatorClient struct {
	mock.Mock
}

// GetValidatorState provides a mock function with given fields: epoch
func (_m *ValidatorClient) GetValidatorState(epoch uint64) (*types.StandardValidatorsResponse, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorState")
	}

	var r0 *types.StandardValidatorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.StandardValidatorsResponse, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.StandardValidatorsResponse); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardValidatorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewValidatorClient creates a new instance of ValidatorClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidatorClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidatorClient {
	mock := &ValidatorClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
