// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	consapi "github.com/gobitfly/beaconchain/pkg/consapi"
	mock "github.com/stretchr/testify/mock"
)

// ClientCreator is an autogenerated mock type for the ClientCreator type
type ClientCreator struct {
	mock.Mock
}

// NewClient provides a mock function with given fields: endpoint
func (_m *ClientCreator) NewClient(endpoint string) consapi.Client {
	ret := _m.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for NewClient")
	}

	var r0 consapi.Client
	if rf, ok := ret.Get(0).(func(string) consapi.Client); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consapi.Client)
		}
	}

	return r0
}

// NewClientCreator creates a new instance of ClientCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientCreator {
	mock := &ClientCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
