// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	types "github.com/gobitfly/beaconchain/pkg/consapi/types"
	mock "github.com/stretchr/testify/mock"
)

// ClientInt is an autogenerated mock type for the ClientInt type
type ClientInt struct {
	mock.Mock
}

// GetAttestationRewards provides a mock function with given fields: epoch
func (_m *ClientInt) GetAttestationRewards(epoch uint64) (*types.StandardAttestationRewardsResponse, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetAttestationRewards")
	}

	var r0 *types.StandardAttestationRewardsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.StandardAttestationRewardsResponse, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.StandardAttestationRewardsResponse); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardAttestationRewardsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlobSidecars provides a mock function with given fields: blockID
func (_m *ClientInt) GetBlobSidecars(blockID interface{}) (*types.StandardBlobSidecarsResponse, error) {
	ret := _m.Called(blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlobSidecars")
	}

	var r0 *types.StandardBlobSidecarsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardBlobSidecarsResponse, error)); ok {
		return rf(blockID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardBlobSidecarsResponse); ok {
		r0 = rf(blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBlobSidecarsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(blockID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockHeader provides a mock function with given fields: blockID
func (_m *ClientInt) GetBlockHeader(blockID interface{}) (*types.StandardBeaconHeaderResponse, error) {
	ret := _m.Called(blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeader")
	}

	var r0 *types.StandardBeaconHeaderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardBeaconHeaderResponse, error)); ok {
		return rf(blockID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardBeaconHeaderResponse); ok {
		r0 = rf(blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBeaconHeaderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(blockID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBlockHeaders provides a mock function with given fields: slot, parentRoot
func (_m *ClientInt) GetBlockHeaders(slot *uint64, parentRoot *interface{}) (*types.StandardBeaconHeadersResponse, error) {
	ret := _m.Called(slot, parentRoot)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockHeaders")
	}

	var r0 *types.StandardBeaconHeadersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*uint64, *interface{}) (*types.StandardBeaconHeadersResponse, error)); ok {
		return rf(slot, parentRoot)
	}
	if rf, ok := ret.Get(0).(func(*uint64, *interface{}) *types.StandardBeaconHeadersResponse); ok {
		r0 = rf(slot, parentRoot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBeaconHeadersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*uint64, *interface{}) error); ok {
		r1 = rf(slot, parentRoot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommittees provides a mock function with given fields: stateID, epoch, index, slot
func (_m *ClientInt) GetCommittees(stateID interface{}, epoch *uint64, index *uint64, slot *uint64) (*types.StandardCommitteesResponse, error) {
	ret := _m.Called(stateID, epoch, index, slot)

	if len(ret) == 0 {
		panic("no return value specified for GetCommittees")
	}

	var r0 *types.StandardCommitteesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, *uint64, *uint64, *uint64) (*types.StandardCommitteesResponse, error)); ok {
		return rf(stateID, epoch, index, slot)
	}
	if rf, ok := ret.Get(0).(func(interface{}, *uint64, *uint64, *uint64) *types.StandardCommitteesResponse); ok {
		r0 = rf(stateID, epoch, index, slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardCommitteesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, *uint64, *uint64, *uint64) error); ok {
		r1 = rf(stateID, epoch, index, slot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEndpoint provides a mock function with no fields
func (_m *ClientInt) GetEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetEvents provides a mock function with given fields: topics
func (_m *ClientInt) GetEvents(topics []types.EventTopic) chan *types.EventResponse {
	ret := _m.Called(topics)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 chan *types.EventResponse
	if rf, ok := ret.Get(0).(func([]types.EventTopic) chan *types.EventResponse); ok {
		r0 = rf(topics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan *types.EventResponse)
		}
	}

	return r0
}

// GetFinalityCheckpoints provides a mock function with given fields: stateID
func (_m *ClientInt) GetFinalityCheckpoints(stateID interface{}) (*types.StandardFinalityCheckpointsResponse, error) {
	ret := _m.Called(stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetFinalityCheckpoints")
	}

	var r0 *types.StandardFinalityCheckpointsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardFinalityCheckpointsResponse, error)); ok {
		return rf(stateID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardFinalityCheckpointsResponse); ok {
		r0 = rf(stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardFinalityCheckpointsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGenesis provides a mock function with no fields
func (_m *ClientInt) GetGenesis() (*types.StandardGenesisResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGenesis")
	}

	var r0 *types.StandardGenesisResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.StandardGenesisResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.StandardGenesisResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardGenesisResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProposalAssignments provides a mock function with given fields: epoch
func (_m *ClientInt) GetProposalAssignments(epoch uint64) (*types.StandardProposerAssignmentsResponse, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetProposalAssignments")
	}

	var r0 *types.StandardProposerAssignmentsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*types.StandardProposerAssignmentsResponse, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *types.StandardProposerAssignmentsResponse); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardProposerAssignmentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProposalRewards provides a mock function with given fields: blockID
func (_m *ClientInt) GetProposalRewards(blockID interface{}) (*types.StandardBlockRewardsResponse, error) {
	ret := _m.Called(blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetProposalRewards")
	}

	var r0 *types.StandardBlockRewardsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardBlockRewardsResponse, error)); ok {
		return rf(blockID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardBlockRewardsResponse); ok {
		r0 = rf(blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBlockRewardsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(blockID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSlot provides a mock function with given fields: blockID
func (_m *ClientInt) GetSlot(blockID interface{}) (*types.StandardBeaconSlotResponse, error) {
	ret := _m.Called(blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetSlot")
	}

	var r0 *types.StandardBeaconSlotResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardBeaconSlotResponse, error)); ok {
		return rf(blockID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardBeaconSlotResponse); ok {
		r0 = rf(blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBeaconSlotResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(blockID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSpec provides a mock function with no fields
func (_m *ClientInt) GetSpec() (*types.StandardSpecResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSpec")
	}

	var r0 *types.StandardSpecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.StandardSpecResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.StandardSpecResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardSpecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetState provides a mock function with given fields: stateID
func (_m *ClientInt) GetState(stateID interface{}) (*types.StandardBeaconStateResponse, error) {
	ret := _m.Called(stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 *types.StandardBeaconStateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardBeaconStateResponse, error)); ok {
		return rf(stateID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardBeaconStateResponse); ok {
		r0 = rf(stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardBeaconStateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncCommitteesAssignments provides a mock function with given fields: epoch, stateID
func (_m *ClientInt) GetSyncCommitteesAssignments(epoch *uint64, stateID interface{}) (*types.StandardSyncCommitteesResponse, error) {
	ret := _m.Called(epoch, stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommitteesAssignments")
	}

	var r0 *types.StandardSyncCommitteesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*uint64, interface{}) (*types.StandardSyncCommitteesResponse, error)); ok {
		return rf(epoch, stateID)
	}
	if rf, ok := ret.Get(0).(func(*uint64, interface{}) *types.StandardSyncCommitteesResponse); ok {
		r0 = rf(epoch, stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardSyncCommitteesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*uint64, interface{}) error); ok {
		r1 = rf(epoch, stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncRewards provides a mock function with given fields: blockID
func (_m *ClientInt) GetSyncRewards(blockID interface{}) (*types.StandardSyncCommitteeRewardsResponse, error) {
	ret := _m.Called(blockID)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncRewards")
	}

	var r0 *types.StandardSyncCommitteeRewardsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardSyncCommitteeRewardsResponse, error)); ok {
		return rf(blockID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardSyncCommitteeRewardsResponse); ok {
		r0 = rf(blockID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardSyncCommitteeRewardsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(blockID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidator provides a mock function with given fields: validatorID, stateID
func (_m *ClientInt) GetValidator(validatorID interface{}, stateID interface{}) (*types.StandardSingleValidatorsResponse, error) {
	ret := _m.Called(validatorID, stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetValidator")
	}

	var r0 *types.StandardSingleValidatorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) (*types.StandardSingleValidatorsResponse, error)); ok {
		return rf(validatorID, stateID)
	}
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) *types.StandardSingleValidatorsResponse); ok {
		r0 = rf(validatorID, stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardSingleValidatorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, interface{}) error); ok {
		r1 = rf(validatorID, stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorBalances provides a mock function with given fields: stateID
func (_m *ClientInt) GetValidatorBalances(stateID interface{}) (*types.StandardValidatorBalancesResponse, error) {
	ret := _m.Called(stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorBalances")
	}

	var r0 *types.StandardValidatorBalancesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*types.StandardValidatorBalancesResponse, error)); ok {
		return rf(stateID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *types.StandardValidatorBalancesResponse); ok {
		r0 = rf(stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardValidatorBalancesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidators provides a mock function with given fields: state, ids, status
func (_m *ClientInt) GetValidators(state interface{}, ids []string, status []types.ValidatorStatus) (*types.StandardValidatorsResponse, error) {
	ret := _m.Called(state, ids, status)

	if len(ret) == 0 {
		panic("no return value specified for GetValidators")
	}

	var r0 *types.StandardValidatorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, []string, []types.ValidatorStatus) (*types.StandardValidatorsResponse, error)); ok {
		return rf(state, ids, status)
	}
	if rf, ok := ret.Get(0).(func(interface{}, []string, []types.ValidatorStatus) *types.StandardValidatorsResponse); ok {
		r0 = rf(state, ids, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardValidatorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, []string, []types.ValidatorStatus) error); ok {
		r1 = rf(state, ids, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientInt creates a new instance of ClientInt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInt(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInt {
	mock := &ClientInt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
