export type ChainFamily =
  | 'Any'
  | 'Arbitrum'
  | 'Base'
  | 'Ethereum'
  | 'Gnosis'
  | 'Optimism'

export const ChainIDs = {
  Any: '0', // to organize data internally (example of use: some ahead-results in the search bar belong to all 'networks',

  ArbitrumNovaEthereum: '42170',
  ArbitrumOneEthereum: '42161',
  ArbitrumOneSepolia: '421614',

  BaseEthereum: '8453',
  BaseSepolia: '84532',
  Chiado: '10200',

  Ethereum: '1',
  Gnosis: '100',

  Holesky: '17000',
  OptimismEthereum: '10',

  OptimismSepolia: '11155420',
  Sepolia: '11155111',
} as const

export type ChainId = typeof ChainIDs[keyof typeof ChainIDs]

export const ChainInfo = {
  [ChainIDs.Any]: {
    clCurrency: 'ETH',
    description: 'Any network',
    elCurrency: 'ETH',
    family: 'Any',
    firstTimestamp: 0,
    L1: ChainIDs.Any,
    mainNet: ChainIDs.Any,
    name: 'Any network',
    nameParts: [
      'Any',
      'network',
    ],
    priority: 0, // data belonging to all networks is displayed first by default
    secondsPerSlot: 12,
    shortName: 'Any',
    slotsPerEpoch: 32,
  },

  [ChainIDs.ArbitrumNovaEthereum]: {
    clCurrency: 'ETH',
    description: 'L2',
    elCurrency: 'ETH',
    family: 'Arbitrum',
    firstTimestamp: 0,
    L1: ChainIDs.Ethereum,
    mainNet: ChainIDs.ArbitrumNovaEthereum,
    name: 'Arbitrum Nova',
    nameParts: [
      'Arbitrum Nova',
      '',
    ],
    priority: 11,
    secondsPerSlot: 0,
    shortName: 'Arbitrum',
    slotsPerEpoch: 0,
  },
  [ChainIDs.ArbitrumOneEthereum]: {
    clCurrency: 'ETH',
    description: 'L2',
    elCurrency: 'ETH',
    family: 'Arbitrum',
    firstTimestamp: 0,
    L1: ChainIDs.Ethereum,
    mainNet: ChainIDs.ArbitrumOneEthereum,
    name: 'Arbitrum One',
    nameParts: [
      'Arbitrum One',
      '',
    ],
    priority: 10,
    secondsPerSlot: 0,
    shortName: 'Arbitrum',
    slotsPerEpoch: 0,
  },
  [ChainIDs.ArbitrumOneSepolia]: {
    clCurrency: 'ETH',
    description: 'Testnet',
    elCurrency: 'ETH',
    family: 'Arbitrum',
    firstTimestamp: 0,
    L1: ChainIDs.Sepolia,
    mainNet: ChainIDs.ArbitrumOneEthereum,
    name: 'Arbitrum Sepolia',
    nameParts: [
      'Arbitrum',
      'Sepolia',
    ],
    priority: 12,
    secondsPerSlot: 0,
    shortName: 'Arbitrum',
    slotsPerEpoch: 0,
  },

  [ChainIDs.BaseEthereum]: {
    clCurrency: 'ETH',
    description: 'L2',
    elCurrency: 'ETH',
    family: 'Base',
    firstTimestamp: 0,
    L1: ChainIDs.Ethereum,
    mainNet: ChainIDs.BaseEthereum,
    name: 'Base',
    nameParts: [
      'Base',
      '',
    ],
    priority: 30,
    secondsPerSlot: 0,
    shortName: 'Base',
    slotsPerEpoch: 0,
  },
  [ChainIDs.BaseSepolia]: {
    clCurrency: 'ETH',
    description: 'Testnet',
    elCurrency: 'ETH',
    family: 'Base',
    firstTimestamp: 0,
    L1: ChainIDs.Sepolia,
    mainNet: ChainIDs.BaseEthereum,
    name: 'Base Sepolia',
    nameParts: [
      'Base',
      'Sepolia',
    ],
    priority: 31,
    secondsPerSlot: 0,
    shortName: 'Base',
    slotsPerEpoch: 0,
  },
  [ChainIDs.Chiado]: {
    clCurrency: 'GNO',
    description: 'Testnet',
    elCurrency: 'xDAI',
    family: 'Gnosis',
    firstTimestamp: 1665396300,
    L1: ChainIDs.Chiado,
    mainNet: ChainIDs.Gnosis,
    name: 'Gnosis Chiado',
    nameParts: [
      'Gnosis',
      'Chiado',
    ],
    priority: 41,
    secondsPerSlot: 5,
    shortName: 'Chiado',
    slotsPerEpoch: 16,
  },

  [ChainIDs.Ethereum]: {
    clCurrency: 'ETH',
    description: 'Mainnet',
    elCurrency: 'ETH',
    family: 'Ethereum',
    firstTimestamp: 1606824023,
    L1: ChainIDs.Ethereum,
    mainNet: ChainIDs.Ethereum,
    name: 'Ethereum',
    nameParts: [
      'Ethereum',
      '',
    ],
    priority: 1,
    secondsPerSlot: 12,
    shortName: 'Ethereum',
    slotsPerEpoch: 32,
  },
  [ChainIDs.Gnosis]: {
    clCurrency: 'GNO',
    description: 'Mainnet',
    elCurrency: 'xDAI',
    family: 'Gnosis',
    firstTimestamp: 1638993340,
    L1: ChainIDs.Gnosis,
    mainNet: ChainIDs.Gnosis,
    name: 'Gnosis',
    nameParts: [
      'Gnosis',
      '',
    ],
    priority: 40,
    secondsPerSlot: 5,
    shortName: 'Gnosis',
    slotsPerEpoch: 16,
  },

  [ChainIDs.Holesky]: {
    clCurrency: 'ETH',
    description: 'Testnet',
    elCurrency: 'ETH',
    family: 'Ethereum',
    firstTimestamp: 1695902400,
    L1: ChainIDs.Holesky,
    mainNet: ChainIDs.Ethereum,
    name: 'Ethereum Holesky',
    nameParts: [
      'Ethereum',
      'Holesky',
    ],
    priority: 2,
    secondsPerSlot: 12,
    shortName: 'Holesky',
    slotsPerEpoch: 32,
  },
  [ChainIDs.OptimismEthereum]: {
    clCurrency: 'ETH',
    description: 'L2',
    elCurrency: 'ETH',
    family: 'Optimism',
    firstTimestamp: 0,
    L1: ChainIDs.Ethereum,
    mainNet: ChainIDs.OptimismEthereum,
    name: 'Optimism',
    nameParts: [
      'Optimism',
      '',
    ],
    priority: 20,
    secondsPerSlot: 0,
    shortName: 'Optimism',
    slotsPerEpoch: 0,
  },

  [ChainIDs.OptimismSepolia]: {
    clCurrency: 'ETH',
    description: 'Testnet',
    elCurrency: 'ETH',
    family: 'Optimism',
    firstTimestamp: 0,
    L1: ChainIDs.Sepolia,
    mainNet: ChainIDs.OptimismEthereum,
    name: 'Optimism Sepolia',
    nameParts: [
      'Optimism',
      'Sepolia',
    ],
    priority: 21,
    secondsPerSlot: 0,
    shortName: 'Optimism',
    slotsPerEpoch: 0,
  },
  [ChainIDs.Sepolia]: {
    clCurrency: 'ETH',
    description: 'Testnet',
    elCurrency: 'ETH',
    family: 'Ethereum',
    firstTimestamp: 1655733600,
    L1: ChainIDs.Sepolia,
    mainNet: ChainIDs.Ethereum,
    name: 'Ethereum Sepolia',
    nameParts: [
      'Ethereum',
      'Sepolia',
    ],
    priority: 3,
    secondsPerSlot: 12,
    shortName: 'Sepolia',
    slotsPerEpoch: 32,
  },
}
