// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
import type { ApiDataResponse } from './common'

//////////
// source: dashboard.go

export interface Dashboard {
  id: number /* uint64 */;
  name: string;
}
export interface UserDashboardsData {
  validator_dashboards: Dashboard[];
  account_dashboards: Dashboard[];
}
export type GetUserDashboardsResponse = ApiDataResponse<UserDashboardsData>;
