// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
import type { Hash, Address } from './common'

//////////
// source: search_types.go

export interface SearchValidator {
  Index: number /* uint64 */;
  PublicKey: Hash;
}
export interface SearchValidatorsByDepositEnsName {
  EnsName: string;
  Validators: number /* uint64 */[];
}
export interface SearchValidatorsByDepositAddress {
  Address: Hash;
  Validators: number /* uint64 */[];
}
export interface SearchValidatorsByWithdrwalCredential {
  WithdrawalCredential: Hash;
  Validators: number /* uint64 */[];
}
export interface SearchValidatorsByWithrawalEnsName {
  EnsName: string;
  Validators: number /* uint64 */[];
}
export interface SearchValidatorsByGraffiti {
  Graffiti: string;
  Validators: number /* uint64 */[];
}
