# Contains Chain configuration overrides for holesky. Depends on `chain/default.yaml` for configurations not specified here.
# Configurations defined here are non-negotiable constants, usually defined as a part of the chain specification. 

ChainSpec:
  CHAIN_ID: 17000
  GENESIS_TIMESTAMP: 1695902400

Forks:
  ALTAIR:
    FORK_VERSION: 0x02017000
    FORK_EPOCH: 0 
  BELLATRIX:
    FORK_VERSION: 0x03017000
    FORK_EPOCH: 0 
  CAPELLA:
    FORK_VERSION: 0x04017000
    FORK_EPOCH: 256
  DENEB:
    FORK_VERSION: 0x40017000