// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsensusRepository is an autogenerated mock type for the ConsensusRepository type
type ConsensusRepository struct {
	mock.Mock
}

// GetDepositsCountForBlockSlot provides a mock function with no fields
func (_m *ConsensusRepository) GetDepositsCountForBlockSlot() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDepositsCountForBlockSlot")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestEpoch provides a mock function with no fields
func (_m *ConsensusRepository) GetLatestEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBlockDeposits provides a mock function with given fields: validatorIndex, pubkey, withdrawalCredentials, balance
func (_m *ConsensusRepository) SaveBlockDeposits(validatorIndex uint64, pubkey []byte, withdrawalCredentials []byte, balance uint64) error {
	ret := _m.Called(validatorIndex, pubkey, withdrawalCredentials, balance)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlockDeposits")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []byte, []byte, uint64) error); ok {
		r0 = rf(validatorIndex, pubkey, withdrawalCredentials, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBlockDepositCount provides a mock function with given fields: count
func (_m *ConsensusRepository) UpdateBlockDepositCount(count int) error {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlockDepositCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBlockDepositsSignature provides a mock function with no fields
func (_m *ConsensusRepository) UpdateBlockDepositsSignature() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlockDepositsSignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusRepository creates a new instance of ConsensusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusRepository {
	mock := &ConsensusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
