// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	types "github.com/gobitfly/beaconchain/pkg/commons/types"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusRepository is an autogenerated mock type for the ConsensusRepository type
type ConsensusRepository struct {
	mock.Mock
}

// DeleteInvalidTags provides a mock function with no fields
func (_m *ConsensusRepository) DeleteInvalidTags() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvalidTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteValidatorTags provides a mock function with no fields
func (_m *ConsensusRepository) DeleteValidatorTags() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteValidatorTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveValidatorTags provides a mock function with given fields: data
func (_m *ConsensusRepository) SaveValidatorTags(data []types.SSVExporterData) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SaveValidatorTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]types.SSVExporterData) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusRepository creates a new instance of ConsensusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusRepository {
	mock := &ConsensusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
