version: "2"
linters:
  enable:
    - unused
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - forbidigo
    - unconvert
    - bodyclose
    - durationcheck
    - errchkjson
    - errname
    - nosprintfhostport
    - nolintlint
    - gosec
    - importas
    - unparam
    - gocritic

  settings:
    unused:
      exported-fields-are-used: true
    forbidigo:
      forbid:
        - pattern: ^logrus\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^logger\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^log\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^fmt\.Print.*$
          msg: Use log.Infof instead
        - pattern: ^fmt\.Printf.*$
          msg: Use log.Infof instead
        - pattern: ^.*ParseForm().*$
          msg: Don't use html forms without proper CSRF protection
        - pattern: ^.*FormValue().*$
          msg: Don't use html forms without proper CSRF protection
    gocognit:
      min-complexity: 65
    depguard:
      rules:
        main-logging:
          list-mode: lax # allow unless explicitly denied
          files:
            - $all
            - "!$test"
            - "!**/internal/log/log.go"
          allow:
            - $gostd
          deny:
            - pkg: log
              desc: "Do not use an external logging library, use pkg/commons/log/log instead"
            - pkg: log/slog
              desc: "Do not use an external logging library, use pkg/commons/log/log instead"
  exclusions:
    paths:
      - cmd/playground