// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	blobstore "github.com/gobitfly/beaconchain/pkg/commons/db2/blobstore"

	mock "github.com/stretchr/testify/mock"
)

// BlobStore is an autogenerated mock type for the BlobStore type
type BlobStore struct {
	mock.Mock
}

// Exist provides a mock function with given fields: ctx, bucket, key
func (_m *BlobStore) Exist(ctx context.Context, bucket string, key string) (bool, error) {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for Exist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, bucket, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, bucket, key
func (_m *BlobStore) Get(ctx context.Context, bucket string, key string) (blobstore.Blob, error) {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 blobstore.Blob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (blobstore.Blob, error)); ok {
		return rf(ctx, bucket, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) blobstore.Blob); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Get(0).(blobstore.Blob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: ctx, bucket, key, blob
func (_m *BlobStore) Put(ctx context.Context, bucket string, key string, blob blobstore.Blob) error {
	ret := _m.Called(ctx, bucket, key, blob)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, blobstore.Blob) error); ok {
		r0 = rf(ctx, bucket, key, blob)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBlobStore creates a new instance of BlobStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBlobStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BlobStore {
	mock := &BlobStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
