// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	consapitypes "github.com/gobitfly/beaconchain/pkg/consapi/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/gobitfly/beaconchain/pkg/commons/types"
)

// QueueClient is an autogenerated mock type for the QueueClient type
type QueueClient struct {
	mock.Mock
}

// GetChainHead provides a mock function with no fields
func (_m *QueueClient) GetChainHead() (*types.ChainHead, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainHead")
	}

	var r0 *types.ChainHead
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ChainHead, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ChainHead); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ChainHead)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingDeposits provides a mock function with given fields: stateID
func (_m *QueueClient) GetPendingDeposits(stateID interface{}) (*consapitypes.StandardBeaconPendingDepositsResponse, error) {
	ret := _m.Called(stateID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingDeposits")
	}

	var r0 *consapitypes.StandardBeaconPendingDepositsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (*consapitypes.StandardBeaconPendingDepositsResponse, error)); ok {
		return rf(stateID)
	}
	if rf, ok := ret.Get(0).(func(interface{}) *consapitypes.StandardBeaconPendingDepositsResponse); ok {
		r0 = rf(stateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consapitypes.StandardBeaconPendingDepositsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(stateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorState provides a mock function with given fields: epoch
func (_m *QueueClient) GetValidatorState(epoch uint64) (*consapitypes.StandardValidatorsResponse, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorState")
	}

	var r0 *consapitypes.StandardValidatorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*consapitypes.StandardValidatorsResponse, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) *consapitypes.StandardValidatorsResponse); ok {
		r0 = rf(epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consapitypes.StandardValidatorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQueueClient creates a new instance of QueueClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueClient {
	mock := &QueueClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
