// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/gobitfly/beaconchain/pkg/consapi/types"
)

// SyncCommitteeClient is an autogenerated mock type for the SyncCommitteeClient type
type SyncCommitteeClient struct {
	mock.Mock
}

// GetSyncCommittee provides a mock function with given fields: stateID, epoch
func (_m *SyncCommitteeClient) GetSyncCommittee(stateID string, epoch uint64) (*types.StandardSyncCommittee, error) {
	ret := _m.Called(stateID, epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommittee")
	}

	var r0 *types.StandardSyncCommittee
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uint64) (*types.StandardSyncCommittee, error)); ok {
		return rf(stateID, epoch)
	}
	if rf, ok := ret.Get(0).(func(string, uint64) *types.StandardSyncCommittee); ok {
		r0 = rf(stateID, epoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.StandardSyncCommittee)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uint64) error); ok {
		r1 = rf(stateID, epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSyncCommitteeClient creates a new instance of SyncCommitteeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncCommitteeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncCommitteeClient {
	mock := &SyncCommitteeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
