export const ERROR_CODE = {
  EFFECTIVE_BALANCE_EXCEEDS_LIMIT: 'EFFECTIVE_BALANCE_EXCEEDS_LIMIT',
  GUEST_DASHBOARD_ID_INVALID: 'GUEST_DASHBOARD_ID_INVALID',
  UNAUTHORIZED_DASHBOARD: 'UNAUTHORIZED_DASHBOARD',
} as const
