{
 "title": "beaconchain",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "path",
    "query": {
     "query": "label_values(http_requests_total,path)"
    }
   },
   { "name": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "health check fails",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(probe_success{network=~\"$network\",instance=~\".*healthz|.*monitoring.*\",project=\"beaconchain\"} < 1) by (instance,network,environment)",
     "legendFormat": "{{network}} {{environment}} | {{instance}}"
    }
   ]
  },
  {
   "title": "avg sec/task",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task,network,service,instance) (\n  rate(task_duration_sum{project=\"beaconchain\",network=~\"$network\"}[20m])\n    /\n  rate(task_duration_count{project=\"beaconchain\",network=~\"$network\"}[20m])\n)",
     "legendFormat": "{{task}} | {{network}} | {{service}} | {{instance}}"
    }
   ]
  },
  {
   "title": "version",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(version{network=~'$network'}) by (version, network, service, environment, instance)",
     "legendFormat": "{{version}} {{service}} {{network}} {{environment}} {{instance}}"
    }
   ]
  },
  {
   "title": "cumulative sec/task/sec [10m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (task, network) (increase(task_duration_sum{network=~\"$network\"}[10m])/600)",
     "legendFormat": "{{network}} | {{task}}"
    }
   ]
  },
  {
   "title": "total req/s/network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (network) (irate(http_requests_total{network=~'$network'}[5m]))",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "req/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (path, service, network) (irate(http_requests_total{network=~'$network',path=~\"$path\"}[5m]))",
       "legendFormat": "{{path}}  | {{service}} | {{network}}"
      }
     ]
    },
    {
     "title": "non200 req/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by(path, network, status_code) (rate(http_requests_total{gce_project=\"etherchain\",status_code!=\"200\",network=~\"$network\",path=~\"$path\"}[10m]))",
       "legendFormat": "{{network}} | {{path}}  | {{status_code}}"
      }
     ]
    },
    {
     "title": "total req/s/network",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "sum by (network) (irate(http_requests_total{network=~'$network'}[5m]))",
       "legendFormat": "{{network}}"
      }
     ]
    },
    {
     "title": "avg s/req",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (network, path, method) (\n  rate(http_requests_duration_sum{network=~\"$network\",path=~\"$path\"}[10m])\n    /\n  rate(http_requests_duration_count{network=~\"$network\",path=~\"$path\"}[10m])\n)",
       "legendFormat": "{{network}} | {{path}}  | {{method}}"
      }
     ]
    },
    {
     "title": "s/req",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sum by(le) (increase(http_requests_duration_bucket{gce_project=\"etherchain\",network=~\"$network\",path=~\"$path\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cumulative sec/req/sec [10m]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (path, network) (increase(http_requests_duration_sum{network=~\"$network\",path=~\"$path\"}[10m])/600)",
       "legendFormat": "{{network}} | {{path}}"
      }
     ]
    },
    {
     "title": "s/req q0.9",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by(le,path,network) (\n  rate(http_requests_duration_bucket{network=~\"$network\",path=~\"$path\"}[10m])\n))",
       "legendFormat": "{{network}} | {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "current versions",
     "type": "table",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "sum(version{project='beaconchain'}) by (version, network, service, instance)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "errors, counters, gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "errors per $__interval",
     "type": "timeseries",
     "description": "errors per hour",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "increase(errors[$__rate_interval]) + on(instance, service, network, environment, project) group_left(version) (0*version)",
       "legendFormat": "{{name}} | {{service}} | {{network}} {{environment}} | {{version}}"
      }
     ]
    },
    {
     "title": "counters total",
     "type": "timeseries",
     "description": "errors per hour",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "counter",
       "legendFormat": "{{name}} | {{service}} | {{instance}} | {{environment}} | {{network}}"
      }
     ]
    },
    {
     "title": "counters rate/$__interval",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
     "targets": [
      {
       "expr": "sum by (name, service, environment, network) (irate(counter[$__interval]))",
       "legendFormat": "{{name}} | {{service}} | {{environment}} | {{network}}"
      }
     ]
    },
    {
     "title": "errors total",
     "type": "timeseries",
     "description": "errors per hour",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
     "targets": [
      {
       "expr": "errors{network=~\"$network\"} + on(instance, service, network, project) group_left(version) (0*version)",
       "legendFormat": "{{name}} | {{service}} | {{network}} {{environment}} | {{version}}"
      }
     ]
    },
    {
     "title": "db_long_running_queries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(delta(db_long_running_queries{project=\"beaconchain\",network=~\"$network\"}[10m])) by (database, query)",
       "legendFormat": "{{database}}: {{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "process_cpu_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (network, instance, service) (irate(process_cpu_seconds_total[5m]))",
       "legendFormat": "{{network}}/{{instance}}/{{service}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "process_mem_resident",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes",
       "legendFormat": "{{service}}/{{network}}/{{instance}}"
      }
     ]
    },
    {
     "title": "process_open_fds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_open_fds",
       "legendFormat": "{{service}}/{{network}}/{{instance}}"
      }
     ]
    },
    {
     "title": "process_uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds",
       "legendFormat": "{{service}}/{{network}}/{{instance}}"
      }
     ]
    },
    {
     "title": "go_goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines",
       "legendFormat": "{{service}}/{{network}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "node_cpu_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "node_network_io/s (sent +, recv -)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total[5m])) by (instance)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(-irate(node_network_receive_bytes_total[5m])) by (instance)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "node_mem_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
       "legendFormat": "{{network}} / {{instance}}"
      }
     ]
    },
    {
     "title": "node_disk_usage_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 254 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(1 - (node_filesystem_avail_bytes/node_filesystem_size_bytes)) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "haproxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "haproxy active servers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{network=~'$network'}",
       "legendFormat": "{{instance}}/{{proxy}}"
      }
     ]
    },
    {
     "title": "haproxy_server_status DOWN",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(haproxy_server_status{state=\"DOWN\"}) by(server, proxy)",
       "legendFormat": "{{proxy}} | {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "v2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2api req/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "targets": [
      {
       "expr": "sum by (path, service, network, environment) (irate(http_requests_total{network=~'$network',path=~\"$path\",service=\"v2api\"}[5m]))",
       "legendFormat": "{{network}} | {{environment}} | {{path}}"
      }
     ]
    },
    {
     "title": "v2api non200 res",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "targets": [
      {
       "expr": "sum by(network, path, status_code) (rate(http_requests_total{project=\"beaconchain\",service=\"v2api\",status_code!=\"200\",network=~\"$network\",path=~\"$path\"}[10m]))",
       "legendFormat": "{{status_code}} | {{network}} | {{path}}"
      }
     ]
    },
    {
     "title": "v2api avg sec/req",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (network, path, method, environment) (\n  rate(http_requests_duration_sum{network=~\"$network\",path=~\"$path\",service=\"v2api\",environment=~\"$environment\"}[10m])\n    / \n  rate(http_requests_duration_count{network=~\"$network\",path=~\"$path\",service=\"v2api\",environment=~\"$environment\"}[10m])\n) ",
       "legendFormat": "{{network}} | {{environment}} | {{path}}"
      }
     ]
    },
    {
     "title": "v2api-staging s/req heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "targets": [
      {
       "expr": "sum by(le) (increase(http_requests_duration_bucket{project=\"beaconchain\",network=~\"$network\",path=~\"$path\",service=\"v2api\",environment=\"staging\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "v2 probe http_duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"probe-beaconchain-lb-holesky-v2|probe-beaconchain-lb-holesky-v2-staging\"}",
       "legendFormat": "{{environment}} | {{instance}}"
      }
     ]
    },
    {
     "title": "v2api-production s/req heatmap",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "targets": [
      {
       "expr": "sum by(le) (increase(http_requests_duration_bucket{project=\"beaconchain\",network=~\"$network\",path=~\"$path\",service=\"v2api\",environment=\"production\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "v2 probe fails",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(probe_success{job=\"probe-beaconchain-lb-holesky-v2\"} < 1) by(instance,network,environment)",
       "legendFormat": "{{network}} | {{environment}} | {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "notifications_sent total (per process-lifetime)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (network, channel, status) (notifications_sent)",
     "legendFormat": "{{network}} | {{channel}} | {{status}}"
    }
   ]
  },
  {
   "title": "notifications_sent per $__interval (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (network, channel, status) (clamp_min(delta(notifications_sent[$__interval]),0))",
     "legendFormat": "{{network}} | {{channel}} | {{status}}"
    }
   ]
  },
  {
   "title": "Pending Notifications in Queue (Per Channel)",
   "type": "timeseries",
   "description": "Number of Notifications in the notifications_queue table which are marked as \"pending\" for each channel type. \n\nNote that \"pending\" notifications will persist in the queue for 1 hour, after which they will be dropped. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "max by(network, channel, status) (notifications_queue_channel_size{status=\"pending\"})",
     "legendFormat": "{{network}} | {{channel}} | {{status}}"
    }
   ]
  },
  {
   "title": "Sent Notifications in Queue (Per Channel)",
   "type": "timeseries",
   "description": "Number of Notifications in the notifications_queue table which are marked as \"sent\" for each channel type. \n\nNote that once a Notification has been \"sent\", it will persist in the table for 30 minutes before being garbage collected. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "max by(network, channel, status) (notifications_queue_channel_size{status=\"sent\"})",
     "legendFormat": "{{network}} | {{channel}} | {{status}}"
    }
   ]
  },
  {
   "title": "Pending Notifications in Queue (Per Event)",
   "type": "timeseries",
   "description": "Number of Notifications in the notifications_queue table which are marked as \"pending\" for each event type. \n\nNote that \"pending\" notifications will persist in the queue for 1 hour, after which they will be dropped. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "max by(network, event_type, status) (notifications_queue_event_size{status=\"pending\"})",
     "legendFormat": "{{network}} | {{event_type}} | {{status}}"
    }
   ]
  },
  {
   "title": "Sent Notifications In Queue (Per Event)",
   "type": "timeseries",
   "description": "Number of Notifications in the notifications_queue table which are marked as \"sent\" for each event type. \n\nNote that once a Notification has been \"sent\", it will persist in the table for 30 minutes before being garbage collected. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "max by(network, event_type, status) (notifications_queue_event_size{status=\"sent\"})",
     "legendFormat": "{{network}} | {{event_type}} | {{status}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Pending (i.e. Dropped) Notifications",
   "type": "timeseries",
   "description": "Notifications that have been deleted from the database because they were pending and went past their 1 hour expiration",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(network, status) (clamp_min(delta(notifications_dropped{status=\"pending\"}[$__interval]), 0))",
     "legendFormat": "{{network}} | {{event_type}} | {{status}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Sent Notifications",
   "type": "timeseries",
   "description": "Notifications that have been deleted from the database because they were sent and went past their 30 min expiration",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by(network, status) (clamp_min(delta(notifications_dropped{status=\"sent\"}[$__interval]), 0))",
     "legendFormat": "{{network}} | {{event_type}} | {{status}}"
    }
   ]
  },
  {
   "title": "Average Pending Notification Duration",
   "type": "timeseries",
   "description": "For the Notifications still in the queue, shows the average amount of time those Notifications have spent in the queue.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (network, channel, event_type) (\n  rate(notifications_queue_pending_duration_seconds_sum{network=~\"$network\",path=~\"$path\"}[10m])\n    /\n  rate(notifications_queue_pending_duration_seconds_count{network=~\"$network\",path=~\"$path\"}[10m])\n)",
     "legendFormat": "{{network}} | {{channel}}  | {{event_type}}"
    }
   ]
  },
  {
   "title": "avg ms/notifications_queue_sent_duration_milliseconds",
   "type": "timeseries",
   "description": "For the \"sent\" Notifications still in the queue, shows the average amount of time those Notifications have spent in the queue.\n\nNote that once sent, Notifications persist in the queue for 30 mins, and so this metric may be delayed by approximately that duration. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (network, channel, event_type) (\n  rate(notifications_queue_sent_duration_seconds_sum{network=~\"$network\"}[10m])\n    /\n  rate(notifications_queue_sent_duration_seconds_count{network=~\"$network\"}[10m])\n)",
     "legendFormat": "{{network}} | {{channel}}  | {{event_type}}"
    }
   ]
  },
  {
   "title": "notifications_queue_pending_duration_milliseconds",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(le, channel, event_type) (increase(notifications_queue_pending_duration_milliseconds_bucket{gce_project=\"etherchain\",network=~\"$network\"}[$__interval]))",
     "legendFormat": "{{le}}ms | {{network}} | {{channel}} | {{event_type}}"
    }
   ]
  },
  {
   "title": "notifications_queue_sent_duration_milliseconds",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum by(le, network, channel, event_type) (increase(notifications_queue_sent_duration_milliseconds_bucket{gce_project=\"etherchain\",network=~\"$network\"}[$__interval]))",
     "legendFormat": "{{le}}ms | {{network}} | {{channel}} | {{event_type}}"
    }
   ]
  }
 ]
}