{
 "title": "exporter v2 schema v2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "query": { "query": "label_values(network)" } },
   {
    "name": "rolling",
    "query": "rolling_1h, rolling_24h, rolling_7d, rolling_30d, rolling_90d, rolling_total"
   },
   { "name": "source", "query": " epoch, hourly, daily, monthly" },
   { "name": "metadata", "query": "grafana-clickhouse-datasource" },
   {
    "name": "database",
    "query": "mainnet, mainnet_re_export_2024_11_08, holesky_re_export_2024_11_09, gnosis, sepolia, clickhouse"
   },
   { "name": "network_meh", "query": { "query": "label_values(network)" } }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "db_version{}", "legendFormat": "__auto" },
    {
     "expr": "version{service=\"v2exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$network_meh",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "network_meh",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(irate(state{state=~\"dashboard_data_exporter_finished_epoch\", network=~\"$network_meh\"}[$__rate_interval])[1536s:]) * 60",
     "legendFormat": "speed"
    },
    {
     "expr": "(state{state=~\"dashboard_data_exporter_latest_safe_epoch\", network=~\"$network_meh\"} - on(network) group_right() state{state=~\"dashboard_data_exporter_finished_epoch\", network=~\"$network_meh\"}) / avg_over_time(irate(state{state=~\"dashboard_data_exporter_finished_epoch\", network=~\"$network_meh\"}[$__rate_interval])[1536s:])",
     "legendFormat": "eta"
    },
    {
     "expr": "(state{state=~\"dashboard_data_exporter_latest_safe_epoch\", network=~\"$network_meh\"} - on(network) group_right() state{state=~\"dashboard_data_exporter_finished_epoch\", network=~\"$network_meh\"})",
     "legendFormat": "lag"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by (state) (\n   state{state=\"dashboard_data_exporter_latest_finalized_epoch\", network=~\"$network\"} - on(network) group_right()\n  state{state=~\"dashboard_data_exporter_.*epoch\", network=~\"$network\"}\n)",
     "legendFormat": "delay {{state}}"
    },
    {
     "expr": "max by (state) (\n  state{state=~\"dashboard_data_exporter_.*epoch\", network=~\"$network\"}\n)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max by (state) (\n   state{state=\"dashboard_data_exporter_latest_finalized_epoch\", network=~\"$network\"} - on(network) group_right()\n  state{state=~\"dashboard_data_exporter_latest_safe_epoch\", network=~\"$network\"}\n)",
     "legendFormat": "delay {{state}}"
    },
    {
     "expr": "max by (task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter.+_overall\",network=~\"$network\"}[768s]) \n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter.+_overall\",network=~\"$network\"}[768s])\n)",
     "legendFormat": "{{task}}"
    },
    {
     "expr": "max by (task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.+_overall\",network=~\"$network\"}[768s]) \n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.+_overall\",network=~\"$network\"}[768s])\n)",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Exporter Metadata",
   "type": "table",
   "description": "shows ",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT * FROM ${database}.\"_exporter_metadata\" FINAL ORDER BY epoch DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Rolling Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max by (state, network) (\n    state{state=~\"dashboard_data_exporter_rolling.*epoch\",network=~\"$network\"} \n)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max by (state, network) (\n   state{state=\"dashboard_data_exporter_latest_finalized_epoch\", network=~\"$network\"} - on(network) group_right()\n  state{state=~\"dashboard_data_exporter_rolling.*epoch\", network=~\"$network\"}\n)\n",
     "legendFormat": "{{state}} delay"
    }
   ]
  },
  {
   "title": "Exporting Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "max by (state, network) (\n    state{state=~\"dashboard_data_exporter_.*epoch\", state!~\"dashboard_data_exporter_rolling.*epoch\",network=~\"$network\"} \n)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "max by (state, network) (\n   state{state=\"dashboard_data_exporter_latest_finalized_epoch\", network=~\"$network\"} - on(network) group_right()\n  state{state=~\"dashboard_data_exporter_.*epoch\", state!~\"dashboard_data_exporter_rolling.*epoch\",network=~\"$network\"} \n)\n",
     "legendFormat": "{{state}} delay"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (network) (\n    avg_over_time(process_resident_memory_bytes{service=\"exporter\", network=~\"$network\", instance=~\".*v2.*\"}[10m])\n)\n",
     "legendFormat": "resident memory avg"
    },
    {
     "expr": "avg by (network) (\n    avg_over_time(go_memstats_alloc_bytes{service=\"exporter\", network=~\"$network\", instance=~\".*v2.*\"}[10m])\n)\n",
     "legendFormat": "alloc memory avg"
    },
    {
     "expr": "max by (network) (\n    max_over_time(process_resident_memory_bytes{service=\"exporter\", network=~\"$network\", instance=~\".*v2.*\"}[10m])\n)\n",
     "legendFormat": "resident memory max"
    },
    {
     "expr": "max by (network) (\n    max_over_time(go_memstats_alloc_bytes{service=\"exporter\", network=~\"$network\", instance=~\".*v2.*\"}[10m])\n)\n",
     "legendFormat": "alloc memory max"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(process_cpu_seconds_total{network=~\"$network\",service=\"exporter\", instance=~\".*v2.*\"}[10m])[$__interval:]\n    )\n)",
     "legendFormat": "delay {{state}}"
    }
   ]
  },
  { "title": "Fetching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "overall fetch duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_fetch.*_overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_fetch.*_overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "overall fetch duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_fetch_.*_overall\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_fetch_.*_overall\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  {
   "title": "single fetch duration breakdown",
   "type": "timeseries",
   "description": "a single fetch is one single thing being fetched (such as one epoch, one block, etc)",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_fetch.*_single\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_fetch.*_single\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "single fetch duration distribution",
   "type": "heatmap",
   "description": "a single fetch is one single thing being fetched (such as one epoch, one block, etc)",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_fetch_.*_single\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_fetch_.*_single\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "overall process duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_process.*_overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_process.*_overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "overall process duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_process_.*_overall\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_process_.*_overall\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  {
   "title": "overall process duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_process.*_single\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_process.*_single\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "single epoch process duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_process_.*_single\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_process_.*_single\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  { "title": "Inserting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "overall insert duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_insert_.*\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_insert_.*\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 17, "w": 12, "x": 12, "y": 126 } },
  {
   "title": "single insert duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"clickhouse_dump__insert_sink_validator_dashboard_data_epoch_.*\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"clickhouse_dump__insert_sink_validator_dashboard_data_epoch_.*\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "single epoch process duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"clickhouse_dump__insert_sink_validator_dashboard_data_epoch_.*\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"clickhouse_dump__insert_sink_validator_dashboard_data_epoch_.*\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  { "title": "Transfering", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "single insert duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_transfer_.*\", network=~\"$network\"}[15m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_transfer_.*\", network=~\"$network\"}[15m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "single epoch process duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 161 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_transfer_.*\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_transfer_.*\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  { "title": "Rolling Update Perf Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "single insert duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*overall\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "single epoch process duration distribution",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "max by(task) (\n    rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*overall\",network=~\"$network\"}[$__rate_interval])\n    /\n    rate(task_duration_count{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*overall\",network=~\"$network\"}[$__rate_interval]))",
     "legendFormat": "{{network}} {{task}}"
    }
   ]
  },
  { "title": "Rolling Update Perf ($rolling)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 }, "repeat": "rolling" },
  {
   "title": "duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*\", task=~\".+$rolling.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*\", task=~\".+$rolling.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 191 },
   "targets": [
    {
     "expr": "sum by(le) (\n    increase(task_duration_bucket{task=~\"dashboard_data_exporter_rolling_validator_dashboard_rolling_.*\", task=~\".+$rolling.+\",network=~\"$network\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 250 } },
  {
   "title": "source transfer duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 251 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling__final_validator_dashboard_data_.*_transfer\", task=~\".+$source.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_rolling__final_validator_dashboard_data_.*_transfer\", task=~\".+$source.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "duration heatmap ($source)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 251 },
   "repeat": "source",
   "targets": [
    {
     "expr": "sum by(le) (\n    increase(task_duration_bucket{task=~\"dashboard_data_exporter_rolling.*\", task=~\".+$source.+\",network=~\"$network\"}[$__rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "source minmax acquire duration breakup",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (task, network) (\n    avg_over_time(\n        rate(task_duration_sum{task=~\"dashboard_data_exporter_rolling__final_validator_dashboard_data_.*_minmax\", task=~\".+$source.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n    /\n    avg_over_time(\n        rate(task_duration_count{task=~\"dashboard_data_exporter_rolling__final_validator_dashboard_data_.*_minmax\", task=~\".+$source.+\", network=~\"$network\"}[10m])[$__interval:]\n    )\n)\n",
     "legendFormat": "{{task}}"
    },
    {}
   ]
  }
 ]
}