// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	db "github.com/gobitfly/beaconchain/pkg/exporter/db"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	types "github.com/gobitfly/beaconchain/pkg/commons/types"
)

// SlotExporterDBRepository is an autogenerated mock type for the SlotExporterDBRepository type
type SlotExporterDBRepository struct {
	mock.Mock
}

// AnalyzeValidatorsTable provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) AnalyzeValidatorsTable(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeValidatorsTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BeginTx provides a mock function with no fields
func (_m *SlotExporterDBRepository) BeginTx() (*sqlx.Tx, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sqlx.Tx, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sqlx.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CacheBlockDepositLookup provides a mock function with no fields
func (_m *SlotExporterDBRepository) CacheBlockDepositLookup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheBlockDepositLookup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheBlockDepositRequestsLookup provides a mock function with no fields
func (_m *SlotExporterDBRepository) CacheBlockDepositRequestsLookup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheBlockDepositRequestsLookup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CommitTx provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) CommitTx(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllNonFinalizedSlots provides a mock function with no fields
func (_m *SlotExporterDBRepository) GetAllNonFinalizedSlots() ([]*db.NonFinalizedSlotsRow, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllNonFinalizedSlots")
	}

	var r0 []*db.NonFinalizedSlotsRow
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*db.NonFinalizedSlotsRow, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*db.NonFinalizedSlotsRow); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.NonFinalizedSlotsRow)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllSlots provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) GetAllSlots(tx *sqlx.Tx) ([]uint64, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSlots")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) ([]uint64, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) []uint64); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(*sqlx.Tx) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastSlot provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) GetLastSlot(tx *sqlx.Tx) (uint64, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSlot")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) (uint64, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) uint64); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(*sqlx.Tx) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorsCurrentState provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) GetValidatorsCurrentState(tx *sqlx.Tx) ([]*types.Validator, error) {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorsCurrentState")
	}

	var r0 []*types.Validator
	var r1 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) ([]*types.Validator, error)); ok {
		return rf(tx)
	}
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) []*types.Validator); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Validator)
		}
	}

	if rf, ok := ret.Get(1).(func(*sqlx.Tx) error); ok {
		r1 = rf(tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidatorsWithMissingBalances provides a mock function with given fields: activationBalanceBatchSize, tx
func (_m *SlotExporterDBRepository) GetValidatorsWithMissingBalances(activationBalanceBatchSize int, tx *sqlx.Tx) ([]db.ActivationEpochValidator, error) {
	ret := _m.Called(activationBalanceBatchSize, tx)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorsWithMissingBalances")
	}

	var r0 []db.ActivationEpochValidator
	var r1 error
	if rf, ok := ret.Get(0).(func(int, *sqlx.Tx) ([]db.ActivationEpochValidator, error)); ok {
		return rf(activationBalanceBatchSize, tx)
	}
	if rf, ok := ret.Get(0).(func(int, *sqlx.Tx) []db.ActivationEpochValidator); ok {
		r0 = rf(activationBalanceBatchSize, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ActivationEpochValidator)
		}
	}

	if rf, ok := ret.Get(1).(func(int, *sqlx.Tx) error); ok {
		r1 = rf(activationBalanceBatchSize, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasEventsForEpoch provides a mock function with given fields: firstSlot, lastSlot
func (_m *SlotExporterDBRepository) HasEventsForEpoch(firstSlot uint64, lastSlot uint64) (bool, error) {
	ret := _m.Called(firstSlot, lastSlot)

	if len(ret) == 0 {
		panic("no return value specified for HasEventsForEpoch")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64) (bool, error)); ok {
		return rf(firstSlot, lastSlot)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64) bool); ok {
		r0 = rf(firstSlot, lastSlot)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = rf(firstSlot, lastSlot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PrepareValidatorsUpdate provides a mock function with given fields: currentState, newState, tx
func (_m *SlotExporterDBRepository) PrepareValidatorsUpdate(currentState *types.Validator, newState *types.Validator, tx *sqlx.Tx) (int, string, error) {
	ret := _m.Called(currentState, newState, tx)

	if len(ret) == 0 {
		panic("no return value specified for PrepareValidatorsUpdate")
	}

	var r0 int
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(*types.Validator, *types.Validator, *sqlx.Tx) (int, string, error)); ok {
		return rf(currentState, newState, tx)
	}
	if rf, ok := ret.Get(0).(func(*types.Validator, *types.Validator, *sqlx.Tx) int); ok {
		r0 = rf(currentState, newState, tx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*types.Validator, *types.Validator, *sqlx.Tx) string); ok {
		r1 = rf(currentState, newState, tx)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(*types.Validator, *types.Validator, *sqlx.Tx) error); ok {
		r2 = rf(currentState, newState, tx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RollbackTx provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) RollbackTx(tx *sqlx.Tx) {
	_m.Called(tx)
}

// SaveBlock provides a mock function with given fields: block, isHeadEpoch, tx
func (_m *SlotExporterDBRepository) SaveBlock(block *types.Block, isHeadEpoch bool, tx *sqlx.Tx) error {
	ret := _m.Called(block, isHeadEpoch, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Block, bool, *sqlx.Tx) error); ok {
		r0 = rf(block, isHeadEpoch, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveEpoch provides a mock function with given fields: epoch, validators, tx
func (_m *SlotExporterDBRepository) SaveEpoch(epoch uint64, validators []*types.Validator, tx *sqlx.Tx) error {
	ret := _m.Called(epoch, validators, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveEpoch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []*types.Validator, *sqlx.Tx) error); ok {
		r0 = rf(epoch, validators, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveNewValidator provides a mock function with given fields: validator, tx
func (_m *SlotExporterDBRepository) SaveNewValidator(validator *types.Validator, tx *sqlx.Tx) error {
	ret := _m.Called(validator, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveNewValidator")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.Validator, *sqlx.Tx) error); ok {
		r0 = rf(validator, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveValidatorQueue provides a mock function with given fields: validators, tx
func (_m *SlotExporterDBRepository) SaveValidatorQueue(validators *types.ValidatorQueue, tx *sqlx.Tx) error {
	ret := _m.Called(validators, tx)

	if len(ret) == 0 {
		panic("no return value specified for SaveValidatorQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ValidatorQueue, *sqlx.Tx) error); ok {
		r0 = rf(validators, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetSlotFinalizationAndStatus provides a mock function with given fields: slot, finalized, status, tx
func (_m *SlotExporterDBRepository) SetSlotFinalizationAndStatus(slot uint64, finalized bool, status string, tx *sqlx.Tx) error {
	ret := _m.Called(slot, finalized, status, tx)

	if len(ret) == 0 {
		panic("no return value specified for SetSlotFinalizationAndStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, bool, string, *sqlx.Tx) error); ok {
		r0 = rf(slot, finalized, status, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransformConsolidationRequests provides a mock function with given fields: firstSlot, lastSlot, tx
func (_m *SlotExporterDBRepository) TransformConsolidationRequests(firstSlot uint64, lastSlot uint64, tx *sqlx.Tx) (int64, error) {
	ret := _m.Called(firstSlot, lastSlot, tx)

	if len(ret) == 0 {
		panic("no return value specified for TransformConsolidationRequests")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) (int64, error)); ok {
		return rf(firstSlot, lastSlot, tx)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) int64); ok {
		r0 = rf(firstSlot, lastSlot, tx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, *sqlx.Tx) error); ok {
		r1 = rf(firstSlot, lastSlot, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransformDepositRequests provides a mock function with given fields: firstSlot, lastSlot, tx
func (_m *SlotExporterDBRepository) TransformDepositRequests(firstSlot uint64, lastSlot uint64, tx *sqlx.Tx) (int64, error) {
	ret := _m.Called(firstSlot, lastSlot, tx)

	if len(ret) == 0 {
		panic("no return value specified for TransformDepositRequests")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) (int64, error)); ok {
		return rf(firstSlot, lastSlot, tx)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) int64); ok {
		r0 = rf(firstSlot, lastSlot, tx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, *sqlx.Tx) error); ok {
		r1 = rf(firstSlot, lastSlot, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransformRemovedExcessBalanceEvents provides a mock function with given fields: firstSlot, lastSlot, tx
func (_m *SlotExporterDBRepository) TransformRemovedExcessBalanceEvents(firstSlot uint64, lastSlot uint64, tx *sqlx.Tx) (int64, error) {
	ret := _m.Called(firstSlot, lastSlot, tx)

	if len(ret) == 0 {
		panic("no return value specified for TransformRemovedExcessBalanceEvents")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) (int64, error)); ok {
		return rf(firstSlot, lastSlot, tx)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) int64); ok {
		r0 = rf(firstSlot, lastSlot, tx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, *sqlx.Tx) error); ok {
		r1 = rf(firstSlot, lastSlot, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransformSwitchToCompoundingRequests provides a mock function with given fields: firstSlot, lastSlot, tx
func (_m *SlotExporterDBRepository) TransformSwitchToCompoundingRequests(firstSlot uint64, lastSlot uint64, tx *sqlx.Tx) (int64, error) {
	ret := _m.Called(firstSlot, lastSlot, tx)

	if len(ret) == 0 {
		panic("no return value specified for TransformSwitchToCompoundingRequests")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) (int64, error)); ok {
		return rf(firstSlot, lastSlot, tx)
	}
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) int64); ok {
		r0 = rf(firstSlot, lastSlot, tx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(uint64, uint64, *sqlx.Tx) error); ok {
		r1 = rf(firstSlot, lastSlot, tx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateActivationEpochBalance provides a mock function with given fields: validatorIndex, balance, tx
func (_m *SlotExporterDBRepository) UpdateActivationEpochBalance(validatorIndex uint64, balance uint64, tx *sqlx.Tx) error {
	ret := _m.Called(validatorIndex, balance, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActivationEpochBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, uint64, *sqlx.Tx) error); ok {
		r0 = rf(validatorIndex, balance, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEpochStatus provides a mock function with given fields: epochParticipationStats, tx
func (_m *SlotExporterDBRepository) UpdateEpochStatus(epochParticipationStats *types.ValidatorParticipation, tx *sqlx.Tx) error {
	ret := _m.Called(epochParticipationStats, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEpochStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ValidatorParticipation, *sqlx.Tx) error); ok {
		r0 = rf(epochParticipationStats, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateQueueDeposits provides a mock function with given fields: tx
func (_m *SlotExporterDBRepository) UpdateQueueDeposits(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQueueDeposits")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateValidators provides a mock function with given fields: queries, totalUpdates, tx
func (_m *SlotExporterDBRepository) UpdateValidators(queries string, totalUpdates int, tx *sqlx.Tx) error {
	ret := _m.Called(queries, totalUpdates, tx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateValidators")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int, *sqlx.Tx) error); ok {
		r0 = rf(queries, totalUpdates, tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSlotExporterDBRepository creates a new instance of SlotExporterDBRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotExporterDBRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotExporterDBRepository {
	mock := &SlotExporterDBRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
