// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SlotExporterCacheRepository is an autogenerated mock type for the SlotExporterCacheRepository type
type SlotExporterCacheRepository struct {
	mock.Mock
}

// GetLatestEpoch provides a mock function with no fields
func (_m *SlotExporterCacheRepository) GetLatestEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestFinalizedEpoch provides a mock function with no fields
func (_m *SlotExporterCacheRepository) GetLatestFinalizedEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestFinalizedEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestProposedSlot provides a mock function with no fields
func (_m *SlotExporterCacheRepository) GetLatestProposedSlot() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestProposedSlot")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestSlot provides a mock function with no fields
func (_m *SlotExporterCacheRepository) GetLatestSlot() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSlot")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetEpochAssignments provides a mock function with given fields: epoch, value, expiration
func (_m *SlotExporterCacheRepository) SetEpochAssignments(epoch uint64, value []byte, expiration time.Duration) error {
	ret := _m.Called(epoch, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetEpochAssignments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []byte, time.Duration) error); ok {
		r0 = rf(epoch, value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLatestEpoch provides a mock function with given fields: epoch
func (_m *SlotExporterCacheRepository) SetLatestEpoch(epoch uint64) error {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for SetLatestEpoch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(epoch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLatestFinalizedEpoch provides a mock function with given fields: epoch
func (_m *SlotExporterCacheRepository) SetLatestFinalizedEpoch(epoch uint64) error {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for SetLatestFinalizedEpoch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(epoch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLatestProposedSlot provides a mock function with given fields: slot
func (_m *SlotExporterCacheRepository) SetLatestProposedSlot(slot uint64) error {
	ret := _m.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for SetLatestProposedSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(slot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLatestSlot provides a mock function with given fields: slot
func (_m *SlotExporterCacheRepository) SetLatestSlot(slot uint64) error {
	ret := _m.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for SetLatestSlot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(slot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetValidatorMapping provides a mock function with given fields: value, expiration
func (_m *SlotExporterCacheRepository) SetValidatorMapping(value []byte, expiration time.Duration) error {
	ret := _m.Called(value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetValidatorMapping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, time.Duration) error); ok {
		r0 = rf(value, expiration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSlotExporterCacheRepository creates a new instance of SlotExporterCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotExporterCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotExporterCacheRepository {
	mock := &SlotExporterCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
