// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	sync "sync"

	mock "github.com/stretchr/testify/mock"

	types "github.com/gobitfly/beaconchain/pkg/commons/types"
)

// SlotExporterBTRepository is an autogenerated mock type for the SlotExporterBTRepository type
type SlotExporterBTRepository struct {
	mock.Mock
}

// GetLastAttestationCache provides a mock function with no fields
func (_m *SlotExporterBTRepository) GetLastAttestationCache() map[uint64]uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastAttestationCache")
	}

	var r0 map[uint64]uint64
	if rf, ok := ret.Get(0).(func() map[uint64]uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}

	return r0
}

// GetLastAttestationCacheMux provides a mock function with no fields
func (_m *SlotExporterBTRepository) GetLastAttestationCacheMux() *sync.Mutex {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastAttestationCacheMux")
	}

	var r0 *sync.Mutex
	if rf, ok := ret.Get(0).(func() *sync.Mutex); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.Mutex)
		}
	}

	return r0
}

// GetValidatorBalanceHistory provides a mock function with given fields: validators, startEpoch, endEpoch
func (_m *SlotExporterBTRepository) GetValidatorBalanceHistory(validators []uint64, startEpoch uint64, endEpoch uint64) (map[uint64][]*types.ValidatorBalance, error) {
	ret := _m.Called(validators, startEpoch, endEpoch)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorBalanceHistory")
	}

	var r0 map[uint64][]*types.ValidatorBalance
	var r1 error
	if rf, ok := ret.Get(0).(func([]uint64, uint64, uint64) (map[uint64][]*types.ValidatorBalance, error)); ok {
		return rf(validators, startEpoch, endEpoch)
	}
	if rf, ok := ret.Get(0).(func([]uint64, uint64, uint64) map[uint64][]*types.ValidatorBalance); ok {
		r0 = rf(validators, startEpoch, endEpoch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64][]*types.ValidatorBalance)
		}
	}

	if rf, ok := ret.Get(1).(func([]uint64, uint64, uint64) error); ok {
		r1 = rf(validators, startEpoch, endEpoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAttestationDuties provides a mock function with given fields: attDuties
func (_m *SlotExporterBTRepository) SaveAttestationDuties(attDuties map[types.Slot]map[types.ValidatorIndex][]types.Slot) error {
	ret := _m.Called(attDuties)

	if len(ret) == 0 {
		panic("no return value specified for SaveAttestationDuties")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[types.Slot]map[types.ValidatorIndex][]types.Slot) error); ok {
		r0 = rf(attDuties)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveSyncCommitteeDuties provides a mock function with given fields: syncDuties
func (_m *SlotExporterBTRepository) SaveSyncCommitteeDuties(syncDuties map[types.Slot]map[types.ValidatorIndex]bool) error {
	ret := _m.Called(syncDuties)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncCommitteeDuties")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[types.Slot]map[types.ValidatorIndex]bool) error); ok {
		r0 = rf(syncDuties)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveValidatorBalances provides a mock function with given fields: epoch, validators
func (_m *SlotExporterBTRepository) SaveValidatorBalances(epoch uint64, validators []*types.Validator) error {
	ret := _m.Called(epoch, validators)

	if len(ret) == 0 {
		panic("no return value specified for SaveValidatorBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []*types.Validator) error); ok {
		r0 = rf(epoch, validators)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSlotExporterBTRepository creates a new instance of SlotExporterBTRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSlotExporterBTRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SlotExporterBTRepository {
	mock := &SlotExporterBTRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
