openapi: 3.0.4
info:
  title: External Service API
  version: 1.0.3

servers:
  - url: https://api-external-616724563735.us-central1.run.app
    description: Staging
  - url: http://localhost:8080
    description: Local development

security:
  - ApiKeyAuth: []
    GCPAuth: []
  
paths:
  /v2/ethereum/validators:
    post:
      tags:
        - Validator
      summary: Returns basic information of a validator
      requestBody:
        $ref: '#/components/requestBodies/validatorsSelector'
      parameters:
        - $ref: '#/components/parameters/chain'
        - $ref: '#/components/parameters/cursor'
        - $ref: '#/components/parameters/pageSize'
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetValidatorMetadataResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpc.Status'
 
  
  ######## Network endpoints ########

  /v2/ethereum/epoch/{epoch}:
    get:
      tags:
        - Network
      summary: Return basic information on the epoch
      parameters:
        - name: epoch
          in: path
          required: true
          schema:
            type: string
            default: latest
        - $ref: '#/components/parameters/chain'
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEpochResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpc.Status'

components:
  # responses:
  # headers:
  # examples:
  # links:
  # callbacks:
  parameters:
    chain:
      name: chain
      in: query
      required: false
      schema:
        type: string
        enum:
          - mainnet
          - hoodi
          - sepolia
        default: mainnet
    cursor:
      name: cursor
      in: query
      required: false
      description: Cursor for pagination
      schema:
        type: string
    pageSize:
      name: page_size
      in: query
      required: false
      description: Number of results to return
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 10
    depositAddress:
      name: deposit_address
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/ELAddress'
    withdrawalAddress:
      name: withdrawal_address
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/ELAddress'
    validator:
      name: validator
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/validatorIndexPubkey'
    startTs:
      name: start
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/startTsParam'
    endTs:
      name: end
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/endTsParam'
    duration:
      name: duration
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/durationParam'

  requestBodies:
    validatorsSelector:
      description: Request body to filter validators
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ValidatorsByDeposit'
              - $ref: '#/components/schemas/ValidatorsByWithdrawal'
              - $ref: '#/components/schemas/ValidatorsByList'

  schemas:
    ValidatorsByDeposit:
      type: object
      properties:
        deposit_address:
          $ref: '#/components/schemas/ELAddress'
      required: [deposit_address]

    ValidatorsByWithdrawal:
      type: object
      properties:
        withdrawal_address:
          $ref: '#/components/schemas/ELAddress'
      required: [withdrawal_address]

    ValidatorsByList:
      type: object
      properties:
        validators:
          $ref: '#/components/schemas/validatorIndexPubkeys'
      required: [validators]
    startTsParam:
      description: '`epoch`, `slot`, `block` or `timestamp` (unix epoch seconds)'
      type: string
      pattern: ^(epoch|slot|block|timestamp)=(0|[1-9][0-9]*)$
      example: epoch=1234
    endTsParam:
      description: '`epoch`, `slot`, `block`, `timestamp` (unix epoch seconds) or `latest`'
      type: string
      pattern: ^((epoch|slot|block|timestamp)=(0|[1-9][0-9]*)|latest)$
      example: timestamp=1757521984
      default: latest
    durationParam:
      description: '`epochs`, `slots`, `blocks` or `time` (h, d, w, m)'
      type: string
      pattern: ^((epochs|slots|blocks)=[1-9][0-9]*|time=[1-9][0-9]*[hdwm])$
      default: time=1d
    ELAddress:
      type: string
      pattern: ^0x[a-fA-F0-9]{40}$
    validatorIndexPubkey:
      description: Validator index or pubkey
      oneOf:
        - type: integer
          minimum: 0
        - type: string
          pattern: ^0x[a-fA-F0-9]{96}$
    validatorIndexPubkeys:
      description: comma-separated list of validator indices or pubkeys
      type: string
      pattern: ^((0|[1-9][0-9]*|0x[a-fA-F0-9]{96}))(,(0|[1-9][0-9]*|0x[a-fA-F0-9]{96}))*$
    BlockTime:
      type: object
      properties:
        block:
          type: integer
          format: int32
        timestamp:
          type: string
          format: int64
    ClEventStatus:
      type: string
      enum:
        - STATUS_UNSPECIFIED
        - queued
        - completed
        - rejected
      default: STATUS_UNSPECIFIED
    Data.Status:
      type: string
      enum:
        - GetValidatorMetadataResponse_UNSPECIFIED
        - pending_initialized
        - pending_queued
        - active_ongoing
        - active_exiting
        - active_slashed
        - exited_unslashed
        - exited_slashed
        - withdrawal_possible
        - withdrawal_done
      default: GetValidatorMetadataResponse_UNSPECIFIED
    Deposits:
      type: object
      properties:
        public_key:
          type: string
          format: byte
        amount:
          type: string
        withdrawal_credential:
          type: string
          format: byte
        signature:
          type: string
          format: byte
        status:
          $ref: '#/components/schemas/ClEventStatus'
        is_processed:
          type: boolean
        slot_queued:
          $ref: '#/components/schemas/SlotTime'
          x-nullable: true
          x-sortable: true
        slot_processed:
          $ref: '#/components/schemas/SlotTime'
          x-nullable: true
          x-sortable: true
        block_queued:
          $ref: '#/components/schemas/BlockTime'
          x-nullable: true
        block_processed:
          $ref: '#/components/schemas/BlockTime'
          x-nullable: true
        is_finalized:
          type: boolean
    DutyStatus:
      type: string
      enum:
        - DutyStatus_STATUS_UNSPECIFIED
        - success
        - missed
        - orphaned
        - scheduled
      default: DutyStatus_STATUS_UNSPECIFIED
    EpochTime:
      type: object
      properties:
        epoch:
          type: integer
          format: int32
        timestamp:
          type: string
          format: int64
  
    GetEpochResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/GetEpochResponse.Data'
      description: A Response containing basic information about the epoch.
    GetEpochResponse.Data:
      type: object
      properties:
        epoch:
          type: integer
          format: int32
        timestamp:
          type: string
          format: int64
        is_finalized:
          type: boolean
        proposed_block_count:
          type: integer
          format: int32
        missed_block_count:
          type: integer
          format: int32
        orphaned_block_count:
          type: integer
          format: int32
        scheduled_block_count:
          type: integer
          format: int32
        voting_participation:
          type: number
          format: float
        sync_participation:
          type: number
          format: float
        attestation_count:
          type: integer
          format: int32
        attestation_slashing_count:
          type: integer
          format: int32
        proposer_slashing_count:
          type: integer
          format: int32
        average_validator_balance:
          type: string
        eligible_ether:
          type: string
        voted_ether:
          type: string
        validator_count:
          type: integer
          format: int32
        voluntary_exit_count:
          type: integer
          format: int32
        total_validator_balance:
          type: string
  
    GetValidatorMetadataResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/GetValidatorMetadataResponse.Data'
        paging:
          $ref: '#/components/schemas/Paging'
      description: A Response containing basic information about the validator.
    GetValidatorMetadataResponse.Data:
      type: object
      properties:
        validator_index:
          type: integer
          format: int32
          x-sortable: true
        pubkey:
          type: string
          format: byte
        slashed:
          type: boolean
        status:
          $ref: '#/components/schemas/Data.Status'
        withdrawal_credentials:
          type: string
          format: byte
        activation_eligibility_epoch:
          type: integer
          format: int32
          x-nullable: true
        activation_epoch:
          type: integer
          format: int32
          x-nullable: true
        exit_epoch:
          type: integer
          format: int32
          x-nullable: true
        withdrawable_epoch:
          type: integer
          format: int32
          x-nullable: true
        effective_balance:
          type: string
        balance:
          type: string
        is_finalized:
          type: boolean

    Paging:
      type: object
      properties:
        prev_cursor:
          type: string
          x-nullable: true
        next_cursor:
          type: string
    SlotTime:
      type: object
      properties:
        slot:
          type: integer
          format: int32
        timestamp:
          type: string
          format: int64
    Validity:
      type: string
      enum:
        - VALIDITY_UNSPECIFIED
        - valid
        - invalid
        - invalid_skipped
      default: VALIDITY_UNSPECIFIED
    Withdrawals:
      type: object
      properties:
        next_withdrawal_index:
          type: string
          format: int64
        validator_index:
          type: string
          format: int64
        recipient_address:
          type: string
          format: byte
        amount:
          type: string
        fee:
          type: string
          x-nullable: true
        status:
          $ref: '#/components/schemas/ClEventStatus'
        is_processed:
          type: boolean
        slot_queued:
          $ref: '#/components/schemas/SlotTime'
          x-nullable: true
          x-sortable: true
        slot_processed:
          $ref: '#/components/schemas/SlotTime'
          x-nullable: true
          x-sortable: true
        block_queued:
          $ref: '#/components/schemas/BlockTime'
          x-nullable: true
        block_processed:
          $ref: '#/components/schemas/BlockTime'
          x-nullable: true
        is_finalized:
          type: boolean
    rpc.Status:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      description: 'Authorization header with value: Bearer <token>'
      name: authorization
      in: header
    GCPAuth:
      type: apiKey
      description: 'Authorization header with value: Bearer <token>'
      name: X-Serverless-Authorization
      in: header
