version: '3'
x-service: &default-service
  image: golang:1.20
  working_dir: /app
  network_mode: "host"
  volumes:
    - ../.:/app
    - /tmp/go-cache:/go
    - /tmp/go-build-cache:/root/.cache/go-build
services:
  build-once:
    <<: *default-service
    profiles:
      - build-once
    command: /bin/bash -c "git config --global --add safe.directory '*' && make -B all"
  indexer:
    <<: *default-service
    command: go run ./cmd/exporter -config /app/local_deployment/config.yml
    environment:
      - INDEXER_ENABLED=true
  eth1indexer:
    <<: *default-service
    command: go run ./cmd/eth1indexer -config /app/local_deployment/config.yml -blocks.concurrency 1 -blocks.tracemode 'geth' -data.concurrency 1 --balances.enabled
  rewards-exporter:
    <<: *default-service
    command: go run ./cmd/rewards_exporter -config /app/local_deployment/config.yml
  statistics:
    <<: *default-service
    command: go run ./cmd/statistics -config /app/local_deployment/config.yml --charts.enabled --graffiti.enabled -validators.enabled
  # frontend-data-updater:
  #   <<: *default-service
  #   command: go run ./cmd/frontend-data-updater -config /app/local_deployment/config.yml
  # frontend:
  #   <<: *default-service
  #   command: go run ./cmd/explorer -config /app/local_deployment/config.yml
  #   environment:
  #     - FRONTEND_ENABLED=true
