version: "2"
linters:
  enable:
    - unused
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - forbidigo
    - unconvert
    - bodyclose
    - durationcheck
    - errchkjson
    - nosprintfhostport
    - nolintlint
    - gosec
    - importas
    - unparam
  disable:
    - staticcheck
    - gosec
    - gocritic
    - errname
  settings:
    depguard:
      rules:
        commons:
          list-mode: lax
          files:
            - '**/commons/**/*.go'
            - '**/commons/*go'
          allow:
            - $gostd
          deny:
            - pkg: github.com/gobitfly/beaconchain/pkg/exporter
              desc: DB must not import
        consapi:
          list-mode: lax
          files:
            - '**/consapi/**/*.go'
            - '**/consapi/*go'
          allow:
            - $gostd
            - github.com/gobitfly/beaconchain/pkg/consapi
          deny:
            - pkg: github.com/gobitfly/beaconchain
              desc: ConsAPI must not import anything from the main package
        db:
          list-mode: lax
          files:
            - '**/commons/db/**/*.go'
            - '**/commons/db/*go'
          allow:
            - $gostd
          deny:
            - pkg: github.com/gobitfly/beaconchain/pkg/consapi
              desc: DB must not import
            - pkg: github.com/gobitfly/beaconchain/pkg/exporter
              desc: DB must not import
            - pkg: net/http
              desc: DB must not import
        main:
          list-mode: lax
          files:
            - $all
            - '!$test'
            - '!**/pkg/exporter/modules/eth1.go'
          allow:
            - $gostd
        main-logging:
          list-mode: lax
          files:
            - $all
            - '!$test'
            - '!**/pkg/commons/log/log.go'
          allow:
            - $gostd
          deny:
            - pkg: log
              desc: Do not use an external logging library, use pkg/commons/log/log instead
            - pkg: log/slog
              desc: Do not use an external logging library, use pkg/commons/log/log instead
    forbidigo:
      forbid:
        - pattern: ^logrus\.Fatalf.*$
          msg: Use log.Fatal instead
        - pattern: ^log\.Fatalf.*$
          msg: Use log.Fatal instead
        - pattern: ^logger\.Fatalf.*$
          msg: Use log.Fatal instead
        - pattern: ^logrus\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^logger\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^log\.Errorf.*$
          msg: Use log.Error instead
        - pattern: ^fmt\.Print.*$
          msg: Use log.Infof instead
        - pattern: ^fmt\.Printf.*$
          msg: Use log.Infof instead
        - pattern: ^.*ParseForm().*$
          msg: Don't use html forms without proper CSRF protection
        - pattern: ^.*FormValue().*$
          msg: Don't use html forms without proper CSRF protection
    gocognit:
      min-complexity: 65
    importas:
      alias:
        - pkg: github.com/gobitfly/beaconchain/pkg/consapi/types
          alias: constypes
        - pkg: github.com/ethereum/go-ethereum/core/types
          alias: gethtypes
        - pkg: github.com/ethereum/go-ethereum/rpc
          alias: gethrpc
        - pkg: github.com/ethereum/go-ethereum
          alias: ethereum
        - pkg: github.com/gobitfly/beaconchain/pkg/exporter/db
          alias: edb
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - cmd/playground
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - cmd/playground
      - third_party$
      - builtin$
      - examples$
