// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	types "github.com/gobitfly/beaconchain/pkg/commons/types"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusDBI is an autogenerated mock type for the ConsensusDBI type
type ConsensusDBI struct {
	mock.Mock
}

// GetSyncCommitteesPeriods provides a mock function with no fields
func (_m *ConsensusDBI) GetSyncCommitteesPeriods() ([]uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommitteesPeriods")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSyncCommitteeData provides a mock function with given fields: data
func (_m *ConsensusDBI) SaveSyncCommitteeData(data []types.SyncCommittee) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncCommitteeData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]types.SyncCommittee) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusDBI creates a new instance of ConsensusDBI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusDBI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusDBI {
	mock := &ConsensusDBI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
