// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsensusDBI is an autogenerated mock type for the ConsensusDBI type
type ConsensusDBI struct {
	mock.Mock
}

// GetCountSoFarSyncCommitteesCountPerValidator provides a mock function with given fields: period
func (_m *ConsensusDBI) GetCountSoFarSyncCommitteesCountPerValidator(period uint64) (float64, error) {
	ret := _m.Called(period)

	if len(ret) == 0 {
		panic("no return value specified for GetCountSoFarSyncCommitteesCountPerValidator")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (float64, error)); ok {
		return rf(period)
	}
	if rf, ok := ret.Get(0).(func(uint64) float64); ok {
		r0 = rf(period)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochValidatorsCount provides a mock function with given fields: epoch
func (_m *ConsensusDBI) GetEpochValidatorsCount(epoch uint64) (uint64, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetEpochValidatorsCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(epoch)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestFinalizedEpoch provides a mock function with no fields
func (_m *ConsensusDBI) GetLatestFinalizedEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestFinalizedEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncCommitteesCountPerValidator provides a mock function with no fields
func (_m *ConsensusDBI) GetSyncCommitteesCountPerValidator() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommitteesCountPerValidator")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPeriodSyncCommitteesCountPerValidator provides a mock function with no fields
func (_m *ConsensusDBI) GetTotalPeriodSyncCommitteesCountPerValidator() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalPeriodSyncCommitteesCountPerValidator")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSyncCommitteesCount provides a mock function with given fields: period, count
func (_m *ConsensusDBI) SaveSyncCommitteesCount(period uint64, count float64) error {
	ret := _m.Called(period, count)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncCommitteesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, float64) error); ok {
		r0 = rf(period, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusDBI creates a new instance of ConsensusDBI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusDBI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusDBI {
	mock := &ConsensusDBI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
