// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConsensusDBI is an autogenerated mock type for the ConsensusDBI type
type ConsensusDBI struct {
	mock.Mock
}

// UpdatePubkeyTags provides a mock function with no fields
func (_m *ConsensusDBI) UpdatePubkeyTags() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdatePubkeyTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusDBI creates a new instance of ConsensusDBI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusDBI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusDBI {
	mock := &ConsensusDBI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
