// For specification see 
// https://protobuf.dev/programming-guides/proto3/
// https://protobuf.dev/reference/go/go-generated/
// https://protobuf.dev/reference/python/python-generated/
syntax = "proto3";

option go_package = "github.com/gobitfly/beaconchain-api/model";

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

//////////////////////////////////////////////////
/////////////// Service Definition ///////////////
//////////////////////////////////////////////////

service BeaconchainApiService {
  
  // Creates a new Validator Dashboard
  rpc CreateValidatorDashboard (CreateValidatorDashboardRequest) returns (CreateValidatorDashboardResponse) {
    option (google.api.http) = {
      post: "/api/validatorDashboard"
    };
  }

  // Retrieves a Validator Dashboard by its Id
  rpc GetValidatorDashboard (GetValidatorDashboardRequest) returns (GetValidatorDashboardResponse) {
    option (google.api.http) = {
      get: "/api/validatorDashboard/{dashboardId}"
    };
  }

  // Retrieves multiple Validator Dashboards by ID or for the entire account
  rpc ListValidatorDashboards (ListValidatorDashboardsRequest) returns (ListValidatorDashboardsResponse) {
    option (google.api.http) = {
      get: "/api/validatorDashboard"
    };
  }

  // Deletes a Validator Dashboard by its Id
  rpc DeleteValidatorDashboard (DeleteValidatorDashboardRequest) returns (DeleteValidatorDashboardResponse) {
    option (google.api.http) = {
      delete: "/api/validatorDashboard/{dashboardId}"
    };
  }

}

/////////////////////////////////////////////////
/////////// Request/Response Definition ////////////
/////////////////////////////////////////////////

// Create
message CreateValidatorDashboardRequest {
  // nil
}

message CreateValidatorDashboardResponse {
  ValidatorDashboard dashboard = 1;
}

// Get
message GetValidatorDashboardRequest {
  string dashboardId = 1;

}

message GetValidatorDashboardResponse {
  ValidatorDashboard dashboard = 1;

}

// List
message ListValidatorDashboardsRequest {
  repeated string dashboardId = 1;
}

message ListValidatorDashboardsResponse {
  repeated ValidatorDashboard dashboards = 1;
}

// Modify
message ModifyValidatorDashboardsRequest {
  string dashboardId = 1;
  // Whether the Dashboard is publicly visible
  optional bool isPublic = 2;
}

message ModifyValidatorDashboardsResponse {
  ValidatorDashboard dashboard = 1;
}

// Delete
message DeleteValidatorDashboardRequest {
  string dashboardId = 1;
}

message DeleteValidatorDashboardResponse {
  // nil; no response
}



//////////////////////////////////////////////////
/////////////// Message Definition ///////////////
//////////////////////////////////////////////////

message ValidatorDashboard {
  string dashboardId = 1;
  bool isPublic = 2;
}



