# Anything placed here will override `service/default.yaml`
# Below settings are for a "default" empty psql database. You shouldn't put any real credentials here. 
# Instead, override these with Environment variables to keep things secure.
readerAdminDatabase:
  username: "postgres"
  dbName: "postgres"
  host: "localhost"
  port: "5432"
  password: "postgres"
  useSSL: false
writerAdminDatabase:
  username: "postgres"
  dbName: "postgres"
  host: "localhost"
  port: "5432"
  password: "postgres"
  useSSL: false

readerChainDatabase:
  username: "postgres"
  dbName: "postgres"
  host: "localhost"
  port: "5432"
  password: "postgres"
  useSSL: false
writerChainDatabase:
  username: "postgres"
  dbName: "postgres"
  host: "localhost"
  port: "5432"
  password: "postgres"
  useSSL: false