# Properties for connecting to the "Staging" environment (as defined by the Staging google project)
readerAdminDatabase:
  username: "beaconchain"
  dbName: "users"
  host: "/cloudsql/staging-456307:us-central1:users-024879cd"
  port: "5432"
  password: "testpassword"
  useSSL: false
writerAdminDatabase:
  username: "beaconchain"
  dbName: "users"
  host: "/cloudsql/staging-456307:us-central1:users-024879cd"
  port: "5432"
  password: "testpassword"
  useSSL: false

readerChainDatabase:
  username: "beaconchain"
  dbName: "hoodi"
  host: "/cloudsql/staging-456307:us-central1:hoodi-d7ab6b26"
  port: "5432"
  password: "testpassword"
  useSSL: false
writerChainDatabase:
  username: "beaconchain"
  dbName: "hoodi"
  host: "/cloudsql/staging-456307:us-central1:hoodi-d7ab6b26"
  port: "5432"
  password: "testpassword"
  useSSL: false