name: Frontend Linter

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - add_frontend_dockerfile
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '*'

jobs:
  frontend-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      working-directory: frontend
      env:
        FA_PRO_KEY: ${{ secrets.FA_PRO_KEY }}
      run: npm --userconfig=".npmrc_ci" ci
    - name: Lint Files
      working-directory: frontend
      run: npm run lint