name: Frontend Check

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - staging
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-check:
    name: lint and typecheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v4
      with:
        node-version-file: 'frontend/.nvmrc'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install Dependencies
      working-directory: frontend
      env:
        FA_PRO_KEY: ${{ secrets.FA_PRO_KEY }}
      run: npm --userconfig=".npmrc_ci" ci
    - name: Lint Files
      working-directory: frontend
      run: npm run lint
    - name: Typecheck Files
      working-directory: frontend
      run: npm run typecheck