name: Lint & Format

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - add_frontend_dockerfile
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - '*'

jobs:
  lint-format:
    name: lint-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: 18
        working-directory: frontend
    - name: Install Dependencies
      run: npm ci
    - name: Check File Format
      run: npm run check-format
    - name: Lint Files
      run: npm run check-style