// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	types "github.com/gobitfly/beaconchain/pkg/commons/types"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusRepository is an autogenerated mock type for the ConsensusRepository type
type ConsensusRepository struct {
	mock.Mock
}

// GetCountSoFarSyncCommitteesCountPerValidator provides a mock function with given fields: period
func (_m *ConsensusRepository) GetCountSoFarSyncCommitteesCountPerValidator(period uint64) (float64, error) {
	ret := _m.Called(period)

	if len(ret) == 0 {
		panic("no return value specified for GetCountSoFarSyncCommitteesCountPerValidator")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (float64, error)); ok {
		return rf(period)
	}
	if rf, ok := ret.Get(0).(func(uint64) float64); ok {
		r0 = rf(period)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDepositsCountForBlockSlot provides a mock function with no fields
func (_m *ConsensusRepository) GetDepositsCountForBlockSlot() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDepositsCountForBlockSlot")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEpochValidatorsCount provides a mock function with given fields: epoch
func (_m *ConsensusRepository) GetEpochValidatorsCount(epoch uint64) (uint64, error) {
	ret := _m.Called(epoch)

	if len(ret) == 0 {
		panic("no return value specified for GetEpochValidatorsCount")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (uint64, error)); ok {
		return rf(epoch)
	}
	if rf, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = rf(epoch)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(epoch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFirstRelayBlock provides a mock function with given fields: tagID
func (_m *ConsensusRepository) GetFirstRelayBlock(tagID string) (types.RelayBlock, error) {
	ret := _m.Called(tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstRelayBlock")
	}

	var r0 types.RelayBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (types.RelayBlock, error)); ok {
		return rf(tagID)
	}
	if rf, ok := ret.Get(0).(func(string) types.RelayBlock); ok {
		r0 = rf(tagID)
	} else {
		r0 = ret.Get(0).(types.RelayBlock)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastRelayBlock provides a mock function with given fields: tagID
func (_m *ConsensusRepository) GetLastRelayBlock(tagID string) (types.RelayBlock, error) {
	ret := _m.Called(tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRelayBlock")
	}

	var r0 types.RelayBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (types.RelayBlock, error)); ok {
		return rf(tagID)
	}
	if rf, ok := ret.Get(0).(func(string) types.RelayBlock); ok {
		r0 = rf(tagID)
	} else {
		r0 = ret.Get(0).(types.RelayBlock)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestEpoch provides a mock function with no fields
func (_m *ConsensusRepository) GetLatestEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestFinalizedEpoch provides a mock function with no fields
func (_m *ConsensusRepository) GetLatestFinalizedEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLatestFinalizedEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNetworkLivenessPreviousHeadEpoch provides a mock function with no fields
func (_m *ConsensusRepository) GetNetworkLivenessPreviousHeadEpoch() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkLivenessPreviousHeadEpoch")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRelays provides a mock function with no fields
func (_m *ConsensusRepository) GetRelays() ([]types.Relay, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRelays")
	}

	var r0 []types.Relay
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]types.Relay, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []types.Relay); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Relay)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncCommitteesCountPerValidator provides a mock function with no fields
func (_m *ConsensusRepository) GetSyncCommitteesCountPerValidator() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommitteesCountPerValidator")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncCommitteesPeriods provides a mock function with no fields
func (_m *ConsensusRepository) GetSyncCommitteesPeriods() ([]uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSyncCommitteesPeriods")
	}

	var r0 []uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []uint64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPeriodSyncCommitteesCountPerValidator provides a mock function with no fields
func (_m *ConsensusRepository) GetTotalPeriodSyncCommitteesCountPerValidator() (uint64, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTotalPeriodSyncCommitteesCountPerValidator")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func() (uint64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveBlockDeposits provides a mock function with given fields: validatorIndex, pubkey, withdrawalCredentials, balance
func (_m *ConsensusRepository) SaveBlockDeposits(validatorIndex uint64, pubkey []byte, withdrawalCredentials []byte, balance uint64) error {
	ret := _m.Called(validatorIndex, pubkey, withdrawalCredentials, balance)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlockDeposits")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []byte, []byte, uint64) error); ok {
		r0 = rf(validatorIndex, pubkey, withdrawalCredentials, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveBlockTagsAndRelays provides a mock function with given fields: tagID, payload
func (_m *ConsensusRepository) SaveBlockTagsAndRelays(tagID string, payload types.BidTrace) error {
	ret := _m.Called(tagID, payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveBlockTagsAndRelays")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, types.BidTrace) error); ok {
		r0 = rf(tagID, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveNetworkLivenessData provides a mock function with given fields: head
func (_m *ConsensusRepository) SaveNetworkLivenessData(head *types.ChainHead) error {
	ret := _m.Called(head)

	if len(ret) == 0 {
		panic("no return value specified for SaveNetworkLivenessData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ChainHead) error); ok {
		r0 = rf(head)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveSyncCommitteeData provides a mock function with given fields: data
func (_m *ConsensusRepository) SaveSyncCommitteeData(data []types.SyncCommittee) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncCommitteeData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]types.SyncCommittee) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveSyncCommitteesCount provides a mock function with given fields: period, count
func (_m *ConsensusRepository) SaveSyncCommitteesCount(period uint64, count float64) error {
	ret := _m.Called(period, count)

	if len(ret) == 0 {
		panic("no return value specified for SaveSyncCommitteesCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, float64) error); ok {
		r0 = rf(period, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBlockDepositCount provides a mock function with given fields: count
func (_m *ConsensusRepository) UpdateBlockDepositCount(count int) error {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlockDepositCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateBlockDepositsSignature provides a mock function with no fields
func (_m *ConsensusRepository) UpdateBlockDepositsSignature() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateBlockDepositsSignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRelay provides a mock function with given fields: tagID, endpoint
func (_m *ConsensusRepository) UpdateRelay(tagID string, endpoint string) error {
	ret := _m.Called(tagID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRelay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(tagID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRelayExportFailureCount provides a mock function with given fields: exportFailureCount, tagID, endpoint
func (_m *ConsensusRepository) UpdateRelayExportFailureCount(exportFailureCount uint64, tagID string, endpoint string) error {
	ret := _m.Called(exportFailureCount, tagID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRelayExportFailureCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, string, string) error); ok {
		r0 = rf(exportFailureCount, tagID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRelayLastExportTry provides a mock function with given fields: tagID, endpoint
func (_m *ConsensusRepository) UpdateRelayLastExportTry(tagID string, endpoint string) error {
	ret := _m.Called(tagID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRelayLastExportTry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(tagID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewConsensusRepository creates a new instance of ConsensusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusRepository {
	mock := &ConsensusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
